//This file is automatically generated

// 用户管理

import { AuthApiController } from '../controller';
export default {
    actions: {
        [AuthApiController.get.method] : {
            summary: '当前登录人信息',
            method: 'get',
            url: (payload) => `/api/platform/user/get`,
            parameters: [],
        },
        [AuthApiController.login.method] : {
            summary: '登录',
            method: 'post',
            url: (payload) => `/api/platform/user/login`,
            parameters: [{'in':'body','name':'user','description':'user','required':true,'schema':{'$ref':'#/definitions/用户登录信息'}}],
        },
        [AuthApiController.logout.method] : {
            summary: '退出',
            method: 'get',
            url: (payload) => `/api/platform/user/logout`,
            parameters: [],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
