//This file is automatically generated

// 字典管理

import { DictApiController } from '../controller';
export default {
    actions: {
        [DictApiController.getDictEntryByDictEntryCode.method] : {
            summary: '根据字典项编码查询字典项目',
            method: 'get',
            url: (payload) => `/api/platform/user/dict/getDictEntryByDictEntryCode/${payload.code}`,
            parameters: [{'name':'code','in':'path','description':'code','required':true,'type':'string'}],
        },
        [DictApiController.getDictEntryByDictEntryId.method] : {
            summary: '根据字典项ID查询字典项目',
            method: 'get',
            url: (payload) => `/api/platform/user/dict/getDictEntryByDictEntryId/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [DictApiController.getDictEntryByDictEntryParentCode.method] : {
            summary: '根据字典项父编码查询字典项目',
            method: 'get',
            url: (payload) => `/api/platform/user/dict/getDictEntryByDictEntryParentCode/${payload.code}`,
            parameters: [{'name':'code','in':'path','description':'code','required':true,'type':'string'}],
        },
        [DictApiController.getDictEntryByDictTypeCode.method] : {
            summary: '根据字典类型编码查询字典项目',
            method: 'get',
            url: (payload) => `/api/platform/user/dict/getDictEntryByDictTypeCode/${payload.code}`,
            parameters: [{'name':'code','in':'path','description':'code','required':true,'type':'string'}],
        },
        [DictApiController.getDictTypeByCode.method] : {
            summary: '根据编码查询字典类型',
            method: 'get',
            url: (payload) => `/api/platform/user/dict/getDictTypeByCode/${payload.code}`,
            parameters: [{'name':'code','in':'path','description':'code','required':true,'type':'string'}],
        },
        [DictApiController.getDictTypeByParentCode.method] : {
            summary: '根据父编码查询字典类型',
            method: 'get',
            url: (payload) => `/api/platform/user/dict/getDictTypeByParentCode/${payload.code}`,
            parameters: [{'name':'code','in':'path','description':'code','required':true,'type':'string'}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
