//This file is automatically generated

// 日程

import { ScheduleFeignImpl } from '../controller';
export default {
    actions: {
        [ScheduleFeignImpl.addParSchedule.method] : {
            summary: '新增一个参与人日程',
            method: 'post',
            url: (payload) => `/api/platform/dal/schedule/addParSchedule/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'日程id','required':true,'type':'string'},{'in':'body','name':'userVO','description':'userVO','required':true,'schema':{'$ref':'#/definitions/UserVO'}}],
        },
        [ScheduleFeignImpl.addSchedule.method] : {
            summary: '新增一个日程',
            method: 'post',
            url: (payload) => `/api/platform/dal/schedule/addSchedule`,
            parameters: [{'in':'body','name':'entity','description':'entity','required':true,'schema':{'$ref':'#/definitions/日程'}}],
        },
        [ScheduleFeignImpl.addScheduleParticipantsList.method] : {
            summary: '批量新增一个日程参与',
            method: 'post',
            url: (payload) => `/api/platform/dal/schedule/addScheduleParticipants`,
            parameters: [{'in':'body','name':'list','description':'list','required':true,'schema':{'type':'array','items':{'$ref':'#/definitions/日程参与'}}}],
        },
        [ScheduleFeignImpl.delParSchedule.method] : {
            summary: '删除一个参与人',
            method: 'delete',
            url: (payload) => `/api/platform/dal/schedule/delParSchedule`,
            parameters: [{'in':'body','name':'entity','description':'entity','required':true,'schema':{'$ref':'#/definitions/日程参与'}}],
        },
        [ScheduleFeignImpl.deleteSchedule.method] : {
            summary: '删除一个日程',
            method: 'delete',
            url: (payload) => `/api/platform/dal/schedule/deleteSchedule/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'主键','required':true,'type':'string'}],
        },
        [ScheduleFeignImpl.deleteScheduleParticipants.method] : {
            summary: '按照条件删除日程参与',
            method: 'delete',
            url: (payload) => `/api/platform/dal/schedule/deleteScheduleParticipants`,
            parameters: [{'in':'body','name':'entity','description':'entity','required':true,'schema':{'$ref':'#/definitions/日程参与'}}],
        },
        [ScheduleFeignImpl.getSchedule.method] : {
            summary: '查询一个日程',
            method: 'get',
            url: (payload) => `/api/platform/dal/schedule/getSchedule/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'主键','required':true,'type':'integer','format':'int32'}],
        },
        [ScheduleFeignImpl.querySchedule.method] : {
            summary: '根据条件查询日程列表',
            method: 'get',
            url: (payload) => `/api/platform/dal/schedule/querySchedule`,
            parameters: [{'in':'body','name':'entity','description':'entity','required':true,'schema':{'$ref':'#/definitions/日程'}}],
        },
        [ScheduleFeignImpl.queryScheduleBetweenDate.method] : {
            summary: '根据条件查询日程列表',
            method: 'get',
            url: (payload) => `/api/platform/dal/schedule/queryScheduleBetweenDate/${payload.startDate}/${payload.endDate}`,
            parameters: [{'name':'endDate','in':'path','description':'结束日','required':true,'type':'string'},{'name':'startDate','in':'path','description':'起始日','required':true,'type':'string'}],
        },
        [ScheduleFeignImpl.queryScheduleParticipantEntity.method] : {
            summary: '查询一个参与人',
            method: 'get',
            url: (payload) => `/api/platform/dal/schedule/getScheduleParticipant}`,
            parameters: [{'in':'body','name':'entity','description':'entity','required':true,'schema':{'$ref':'#/definitions/日程参与'}}],
        },
        [ScheduleFeignImpl.updateSchedule.method] : {
            summary: '修改一个日程',
            method: 'put',
            url: (payload) => `/api/platform/dal/schedule/updateSchedule`,
            parameters: [{'in':'body','name':'entity','description':'entity','required':true,'schema':{'$ref':'#/definitions/日程'}}],
        },
        [ScheduleFeignImpl.updateScheduleParticipants.method] : {
            summary: '修改一个日程参与',
            method: 'put',
            url: (payload) => `/api/platform/dal/schedule/updateScheduleParticipants`,
            parameters: [{'in':'body','name':'entity','description':'entity','required':true,'schema':{'$ref':'#/definitions/日程参与'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
