//This file is automatically generated

 //帮助中心
let HelpControllerImpl = {
    __name: 'HelpControllerImpl',
    AddDemandFeedbackReply: {controller: 'HelpControllerImpl' , method: 'AddDemandFeedbackReply'}, // 新增一个需求反馈回复
    addDemandFeedback: {controller: 'HelpControllerImpl' , method: 'addDemandFeedback'}, // 新增一个需求反馈
    queryByIdJoinReply: {controller: 'HelpControllerImpl' , method: 'queryByIdJoinReply'}, // 根据ID查询一个需求反馈
    queryByTitle: {controller: 'HelpControllerImpl' , method: 'queryByTitle'}, // 根据标题模糊查询所有常见问题
    queryDemandFeedback: {controller: 'HelpControllerImpl' , method: 'queryDemandFeedback'}, // 查询所有需求反馈
    queryProductIntroduction: {controller: 'HelpControllerImpl' , method: 'queryProductIntroduction'}, // 查询所有产品介绍
    updateDemandFeedbackType: {controller: 'HelpControllerImpl' , method: 'updateDemandFeedbackType'}, // 更改需求反馈的状态
};
 //日程
let ScheduleControllerImpl = {
    __name: 'ScheduleControllerImpl',
    addParSchedule: {controller: 'ScheduleControllerImpl' , method: 'addParSchedule'}, // 新增一个参与人
    addSchedule: {controller: 'ScheduleControllerImpl' , method: 'addSchedule'}, // 新增一个日程
    delParSchedule: {controller: 'ScheduleControllerImpl' , method: 'delParSchedule'}, // 删除一个参与人
    deleteSchedule: {controller: 'ScheduleControllerImpl' , method: 'deleteSchedule'}, // 删除一个日程
    queryScheduleByMM: {controller: 'ScheduleControllerImpl' , method: 'queryScheduleByMM'}, // 根据时间区间查询日程列表
    updateAgree: {controller: 'ScheduleControllerImpl' , method: 'updateAgree'}, // 确认同意或拒绝
    updateSchedule: {controller: 'ScheduleControllerImpl' , method: 'updateSchedule'}, // 修改一个日程
};
 //预约中心
let BarberControllerImpl = {
    __name: 'BarberControllerImpl',
    addBarber: {controller: 'BarberControllerImpl' , method: 'addBarber'}, // 发布理发室
    addBarberUser: {controller: 'BarberControllerImpl' , method: 'addBarberUser'}, // 预约理发室
    deleteBarber: {controller: 'BarberControllerImpl' , method: 'deleteBarber'}, // 删除一个发布的理发室信息
    queryAll: {controller: 'BarberControllerImpl' , method: 'queryAll'}, // 管理员查询全部预约情况
    queryByMonth: {controller: 'BarberControllerImpl' , method: 'queryByMonth'}, // 根据日期进行查询预约情况
    queryByState: {controller: 'BarberControllerImpl' , method: 'queryByState'}, // 根据预约状态查询理发室的预约情况
    queryByTypeAndDate: {controller: 'BarberControllerImpl' , method: 'queryByTypeAndDate'}, // 根据预约类型和日期查询理发室的预约情况  名额
    updateBarber: {controller: 'BarberControllerImpl' , method: 'updateBarber'}, // 修改发布的理发室信息
    updateCancel: {controller: 'BarberControllerImpl' , method: 'updateCancel'}, // 取消理发室预约
    updateSign: {controller: 'BarberControllerImpl' , method: 'updateSign'}, // 理发室预约签到
};
 //pipe-report-controller
let PipeReportController = {
    __name: 'PipeReportController',
    create: {controller: 'PipeReportController' , method: 'create'}, // create
    deleteById: {controller: 'PipeReportController' , method: 'deleteById'}, // deleteById
    findAll: {controller: 'PipeReportController' , method: 'findAll'}, // findAll
    findByCriteria: {controller: 'PipeReportController' , method: 'findByCriteria'}, // findByCriteria
    getById: {controller: 'PipeReportController' , method: 'getById'}, // getById
    pagingAll: {controller: 'PipeReportController' , method: 'pagingAll'}, // pagingAll
    pagingByCriteria: {controller: 'PipeReportController' , method: 'pagingByCriteria'}, // pagingByCriteria
    update: {controller: 'PipeReportController' , method: 'update'}, // update
};
 //人员健康管理
let HealthApiController = {
    __name: 'HealthApiController',
    getHealthInfo: {controller: 'HealthApiController' , method: 'getHealthInfo'}, // 获取人员健康信息
    updateHealthInfo: {controller: 'HealthApiController' , method: 'updateHealthInfo'}, // 根据人员id更新人员健康录入信息
};
 //字典管理
let DictApiController = {
    __name: 'DictApiController',
    getDictEntryByDictEntryCode: {controller: 'DictApiController' , method: 'getDictEntryByDictEntryCode'}, // 根据字典项编码查询字典项目
    getDictEntryByDictEntryId: {controller: 'DictApiController' , method: 'getDictEntryByDictEntryId'}, // 根据字典项ID查询字典项目
    getDictEntryByDictEntryParentCode: {controller: 'DictApiController' , method: 'getDictEntryByDictEntryParentCode'}, // 根据字典项父编码查询字典项目
    getDictEntryByDictTypeCode: {controller: 'DictApiController' , method: 'getDictEntryByDictTypeCode'}, // 根据字典类型编码查询字典项目
    getDictTypeByCode: {controller: 'DictApiController' , method: 'getDictTypeByCode'}, // 根据编码查询字典类型
    getDictTypeByParentCode: {controller: 'DictApiController' , method: 'getDictTypeByParentCode'}, // 根据父编码查询字典类型
};
 //用户管理
let AuthApiController = {
    __name: 'AuthApiController',
    deleteAttr: {controller: 'AuthApiController' , method: 'deleteAttr'}, // 删除用户属性
    deleteAttrs: {controller: 'AuthApiController' , method: 'deleteAttrs'}, // 删除用户属性列表
    get: {controller: 'AuthApiController' , method: 'get'}, // 当前登录人信息
    getAttr: {controller: 'AuthApiController' , method: 'getAttr'}, // 获得用户具体属性
    getAttrs: {controller: 'AuthApiController' , method: 'getAttrs'}, // 获得用户属性列表
    login: {controller: 'AuthApiController' , method: 'login'}, // 登录
    logout: {controller: 'AuthApiController' , method: 'logout'}, // 退出
    updateAttr: {controller: 'AuthApiController' , method: 'updateAttr'}, // 更新用户属性
    updateAttrs: {controller: 'AuthApiController' , method: 'updateAttrs'}, // 更新用户属性列表
};
 //员工卡
let WorkCartControllerImpl = {
    __name: 'WorkCartControllerImpl',
    addDalance: {controller: 'WorkCartControllerImpl' , method: 'addDalance'}, // 充值
    cancelledCard: {controller: 'WorkCartControllerImpl' , method: 'cancelledCard'}, // 注销
    getReviewList: {controller: 'WorkCartControllerImpl' , method: 'getReviewList'}, // 获取审批列表
    getWorkCard: {controller: 'WorkCartControllerImpl' , method: 'getWorkCard'}, // 获取当前员工的员工卡状态
    open: {controller: 'WorkCartControllerImpl' , method: 'open'}, // 员工开卡
    queryWorkCardAll: {controller: 'WorkCartControllerImpl' , method: 'queryWorkCardAll'}, // 查询所有员工卡信息
    queryWorkCardApplyRecord: {controller: 'WorkCartControllerImpl' , method: 'queryWorkCardApplyRecord'}, // 查询员工卡申请记录
    queryWorkCardRecord: {controller: 'WorkCartControllerImpl' , method: 'queryWorkCardRecord'}, // 查询员工卡记录
    replacement: {controller: 'WorkCartControllerImpl' , method: 'replacement'}, // 补卡
    reportTheLoss: {controller: 'WorkCartControllerImpl' , method: 'reportTheLoss'}, // 挂失
    review: {controller: 'WorkCartControllerImpl' , method: 'review'}, // 审核
    updateWorkCard: {controller: 'WorkCartControllerImpl' , method: 'updateWorkCard'}, // 修改员工卡信息
};
 //文化建设
let CulturalControllerImpl = {
    __name: 'CulturalControllerImpl',
    addCommunicationCircle: {controller: 'CulturalControllerImpl' , method: 'addCommunicationCircle'}, // 添加一个交流圈（发帖子）
    allPageSreach: {controller: 'CulturalControllerImpl' , method: 'allPageSreach'}, // 根据分页数据查询公告列表、企业新闻、交流圈
    deleteCommunicationCircle: {controller: 'CulturalControllerImpl' , method: 'deleteCommunicationCircle'}, // 根据主键删除交流圈
    fabulousCommunicationCircle: {controller: 'CulturalControllerImpl' , method: 'fabulousCommunicationCircle'}, // 根据交流圈主键点赞或取消点赞
    getCommunicationCircleEntity: {controller: 'CulturalControllerImpl' , method: 'getCommunicationCircleEntity'}, // 根据交流圈主键获取交流圈详细信息与评论列表信息
    getNotice: {controller: 'CulturalControllerImpl' , method: 'getNotice'}, // 根据主键查询公告
    noticePageSreach: {controller: 'CulturalControllerImpl' , method: 'noticePageSreach'}, // 根据分页数据查询公告列表
};

export {
    HelpControllerImpl,
    ScheduleControllerImpl,
    BarberControllerImpl,
    PipeReportController,
    HealthApiController,
    DictApiController,
    AuthApiController,
    WorkCartControllerImpl,
    CulturalControllerImpl,
};
