//This file is automatically generated

 //pipe-report-controller
let PipeReportController = {
    __name: 'PipeReportController',
    create: {controller: 'PipeReportController' , method: 'create'}, // create
    deleteById: {controller: 'PipeReportController' , method: 'deleteById'}, // deleteById
    findAll: {controller: 'PipeReportController' , method: 'findAll'}, // findAll
    findByCriteria: {controller: 'PipeReportController' , method: 'findByCriteria'}, // findByCriteria
    getById: {controller: 'PipeReportController' , method: 'getById'}, // getById
    pagingAll: {controller: 'PipeReportController' , method: 'pagingAll'}, // pagingAll
    pagingByCriteria: {controller: 'PipeReportController' , method: 'pagingByCriteria'}, // pagingByCriteria
    update: {controller: 'PipeReportController' , method: 'update'}, // update
};
 //人员健康管理
let HealthApiController = {
    __name: 'HealthApiController',
    getHealthInfo: {controller: 'HealthApiController' , method: 'getHealthInfo'}, // 获取人员健康信息
    updateHealthInfo: {controller: 'HealthApiController' , method: 'updateHealthInfo'}, // 根据人员id更新人员健康录入信息
};
 //字典管理
let DictApiController = {
    __name: 'DictApiController',
    getDictEntryByDictEntryCode: {controller: 'DictApiController' , method: 'getDictEntryByDictEntryCode'}, // 根据字典项编码查询字典项目
    getDictEntryByDictEntryId: {controller: 'DictApiController' , method: 'getDictEntryByDictEntryId'}, // 根据字典项ID查询字典项目
    getDictEntryByDictEntryParentCode: {controller: 'DictApiController' , method: 'getDictEntryByDictEntryParentCode'}, // 根据字典项父编码查询字典项目
    getDictEntryByDictTypeCode: {controller: 'DictApiController' , method: 'getDictEntryByDictTypeCode'}, // 根据字典类型编码查询字典项目
    getDictTypeByCode: {controller: 'DictApiController' , method: 'getDictTypeByCode'}, // 根据编码查询字典类型
    getDictTypeByParentCode: {controller: 'DictApiController' , method: 'getDictTypeByParentCode'}, // 根据父编码查询字典类型
};
 //用户管理
let AuthApiController = {
    __name: 'AuthApiController',
    deleteAttr: {controller: 'AuthApiController' , method: 'deleteAttr'}, // 删除用户属性
    deleteAttrs: {controller: 'AuthApiController' , method: 'deleteAttrs'}, // 删除用户属性列表
    get: {controller: 'AuthApiController' , method: 'get'}, // 当前登录人信息
    getAttr: {controller: 'AuthApiController' , method: 'getAttr'}, // 获得用户具体属性
    getAttrs: {controller: 'AuthApiController' , method: 'getAttrs'}, // 获得用户属性列表
    login: {controller: 'AuthApiController' , method: 'login'}, // 登录
    logout: {controller: 'AuthApiController' , method: 'logout'}, // 退出
    updateAttr: {controller: 'AuthApiController' , method: 'updateAttr'}, // 更新用户属性
    updateAttrs: {controller: 'AuthApiController' , method: 'updateAttrs'}, // 更新用户属性列表
};
 //文化建设
let CulturalControllerImpl = {
    __name: 'CulturalControllerImpl',
    addCommunicationCircle: {controller: 'CulturalControllerImpl' , method: 'addCommunicationCircle'}, // 添加一个交流圈（发帖子）
    allPageSreach: {controller: 'CulturalControllerImpl' , method: 'allPageSreach'}, // 根据分页数据查询公告列表、企业新闻、交流圈
    deleteCommunicationCircle: {controller: 'CulturalControllerImpl' , method: 'deleteCommunicationCircle'}, // 根据主键删除交流圈
    fabulousCommunicationCircle: {controller: 'CulturalControllerImpl' , method: 'fabulousCommunicationCircle'}, // 根据交流圈主键点赞或取消点赞
    getCommunicationCircleEntity: {controller: 'CulturalControllerImpl' , method: 'getCommunicationCircleEntity'}, // 根据交流圈主键获取交流圈详细信息与评论列表信息
    noticePageSreach: {controller: 'CulturalControllerImpl' , method: 'noticePageSreach'}, // 根据分页数据查询公告列表
};
 //日程
let ScheduleControllerImpl = {
    __name: 'ScheduleControllerImpl',
    addParSchedule: {controller: 'ScheduleControllerImpl' , method: 'addParSchedule'}, // 新增一个参与人日程
    addSchedule: {controller: 'ScheduleControllerImpl' , method: 'addSchedule'}, // 新增一个日程
    deleteSchedule: {controller: 'ScheduleControllerImpl' , method: 'deleteSchedule'}, // 删除一个日程
    queryScheduleByMM: {controller: 'ScheduleControllerImpl' , method: 'queryScheduleByMM'}, // 根据时间区间查询日程列表
    updateAgree: {controller: 'ScheduleControllerImpl' , method: 'updateAgree'}, // 确认同意或拒绝
    updateSchedule: {controller: 'ScheduleControllerImpl' , method: 'updateSchedule'}, // 修改一个日程
};
 //帮助中心
let HelpControllerImpl = {
    __name: 'HelpControllerImpl',
    AddDemandFeedbackReply: {controller: 'HelpControllerImpl' , method: 'AddDemandFeedbackReply'}, // 新增一个需求反馈回复
    addDemandFeedback: {controller: 'HelpControllerImpl' , method: 'addDemandFeedback'}, // 新增一个需求反馈
    queryByIdJoinReply: {controller: 'HelpControllerImpl' , method: 'queryByIdJoinReply'}, // 根据ID查询一个需求反馈
    queryByTitle: {controller: 'HelpControllerImpl' , method: 'queryByTitle'}, // 根据标题模糊查询所有常见问题
    queryDemandFeedback: {controller: 'HelpControllerImpl' , method: 'queryDemandFeedback'}, // 查询所有需求反馈
    queryProductIntroduction: {controller: 'HelpControllerImpl' , method: 'queryProductIntroduction'}, // 查询所有产品介绍
    updateDemandFeedbackType: {controller: 'HelpControllerImpl' , method: 'updateDemandFeedbackType'}, // 更改需求反馈的状态
};
 //员工卡
let WorkCardFeignImpl = {
    __name: 'WorkCardFeignImpl',
    addWorkCard: {controller: 'WorkCardFeignImpl' , method: 'addWorkCard'}, // 新增一个员工卡
    addWorkCardRecord: {controller: 'WorkCardFeignImpl' , method: 'addWorkCardRecord'}, // 新增一个员工卡记录
    getWorkCard: {controller: 'WorkCardFeignImpl' , method: 'getWorkCard'}, // 查询一个员工卡
    queryWorkCard: {controller: 'WorkCardFeignImpl' , method: 'queryWorkCard'}, // 使用code查询一个员工卡
    queryWorkCardRecord: {controller: 'WorkCardFeignImpl' , method: 'queryWorkCardRecord'}, // 查询员工卡记录
    replacement: {controller: 'WorkCardFeignImpl' , method: 'replacement'}, // 员工卡补卡
    updateWorkCard: {controller: 'WorkCardFeignImpl' , method: 'updateWorkCard'}, // 修改一个员工卡
};
 //帮助中心
let HelpFeignImpl = {
    __name: 'HelpFeignImpl',
    AddDemandFeedbackReply: {controller: 'HelpFeignImpl' , method: 'AddDemandFeedbackReply'}, // 新增一个需求反馈回复
    addDemandFeedback: {controller: 'HelpFeignImpl' , method: 'addDemandFeedback'}, // 新增一个需求反馈
    getDemandFeedback: {controller: 'HelpFeignImpl' , method: 'getDemandFeedback'}, // 根据ID查询一条需求反���
    queryByTitle: {controller: 'HelpFeignImpl' , method: 'queryByTitle'}, // 根据标题模糊查询所有常见问题
    queryDemandFeedback: {controller: 'HelpFeignImpl' , method: 'queryDemandFeedback'}, // 查询所有需求反馈
    queryDemandFeedbackReply: {controller: 'HelpFeignImpl' , method: 'queryDemandFeedbackReply'}, // 根据需求反馈ID查询需求反馈回复列表
    queryProductIntroduction: {controller: 'HelpFeignImpl' , method: 'queryProductIntroduction'}, // 查询所有产品介绍
    queryUserDemandFeedback: {controller: 'HelpFeignImpl' , method: 'queryUserDemandFeedback'}, // 查询当前用户的所有需求反馈
    updateDemandFeedback: {controller: 'HelpFeignImpl' , method: 'updateDemandFeedback'}, // 修改一个需求反馈
};
 //文化建设
let CulturalFeignImpl = {
    __name: 'CulturalFeignImpl',
    addCommunicationCircle: {controller: 'CulturalFeignImpl' , method: 'addCommunicationCircle'}, // 添加一个交流圈（发帖子）
    deleteCommunicationCircle: {controller: 'CulturalFeignImpl' , method: 'deleteCommunicationCircle'}, // 根据主键删除交流圈
    fabulousCommunicationCircle: {controller: 'CulturalFeignImpl' , method: 'fabulousCommunicationCircle'}, // 根据交流圈主键点赞或取消点赞
    getCommunicationCircle: {controller: 'CulturalFeignImpl' , method: 'getCommunicationCircle'}, // 根据交流圈主键查询一个交流圈
    getCommunicationCircleForComment: {controller: 'CulturalFeignImpl' , method: 'getCommunicationCircleForComment'}, // 根据交流圈主键查询评论列表
    journalismPageSreach: {controller: 'CulturalFeignImpl' , method: 'journalismPageSreach'}, // 根据分页数据查询公告列表
    noticePageSreach: {controller: 'CulturalFeignImpl' , method: 'noticePageSreach'}, // 根据分页数据查询公告列表
    queryByPageAndReleaseTimeDescAndChoice: {controller: 'CulturalFeignImpl' , method: 'queryByPageAndReleaseTimeDescAndChoice'}, // 交流圈连接交流圈点赞查询：分页、发布时间排序、精选
    queryByPageAndTopTimeDescReleaseTimeDesc: {controller: 'CulturalFeignImpl' , method: 'queryByPageAndTopTimeDescReleaseTimeDesc'}, // 交流圈连接交流圈点赞查询：置顶时间+发布时间排序、分页
    queryCommunicationCircleByPageAndFabulousPlusCountSort: {controller: 'CulturalFeignImpl' , method: 'queryCommunicationCircleByPageAndFabulousPlusCountSort'}, // 交流圈连接交流圈点赞查询：分页、热门排序
};
 //日程
let ScheduleFeignImpl = {
    __name: 'ScheduleFeignImpl',
    addParSchedule: {controller: 'ScheduleFeignImpl' , method: 'addParSchedule'}, // 新增一个参与人日程
    addSchedule: {controller: 'ScheduleFeignImpl' , method: 'addSchedule'}, // 新增一个日程
    addScheduleParticipantsList: {controller: 'ScheduleFeignImpl' , method: 'addScheduleParticipantsList'}, // 批量新增一个日程参与
    deleteSchedule: {controller: 'ScheduleFeignImpl' , method: 'deleteSchedule'}, // 删除一个日程
    deleteScheduleParticipants: {controller: 'ScheduleFeignImpl' , method: 'deleteScheduleParticipants'}, // 按照条件删除日程参与
    getSchedule: {controller: 'ScheduleFeignImpl' , method: 'getSchedule'}, // 查询一个日程
    querySchedule: {controller: 'ScheduleFeignImpl' , method: 'querySchedule'}, // 根据条件查询日程列表
    queryScheduleBetweenDate: {controller: 'ScheduleFeignImpl' , method: 'queryScheduleBetweenDate'}, // 根据条件查询日程列表
    updateSchedule: {controller: 'ScheduleFeignImpl' , method: 'updateSchedule'}, // 修改一个日程
    updateScheduleParticipants: {controller: 'ScheduleFeignImpl' , method: 'updateScheduleParticipants'}, // 修改一个日程参与
};
 //用户属性API
let UserAttrApiFeignImpl = {
    __name: 'UserAttrApiFeignImpl',
    delete: {controller: 'UserAttrApiFeignImpl' , method: 'delete'}, // 根据用户ID,删除属性名称列表
    get: {controller: 'UserAttrApiFeignImpl' , method: 'get'}, // 根据用户ID获得属性列表
    get: {controller: 'UserAttrApiFeignImpl' , method: 'get'}, // 根据用户ID获得属性
    update: {controller: 'UserAttrApiFeignImpl' , method: 'update'}, // 更新��户属性列表
};

export {
    PipeReportController,
    HealthApiController,
    DictApiController,
    AuthApiController,
    CulturalControllerImpl,
    ScheduleControllerImpl,
    HelpControllerImpl,
    WorkCardFeignImpl,
    HelpFeignImpl,
    CulturalFeignImpl,
    ScheduleFeignImpl,
    UserAttrApiFeignImpl,
};
