//This file is automatically generated

// agent

import { agent } from '../controller';
export default {
    actions: {
        [agent.addAgent.method] : {
            summary: 'addAgent',
            method: 'post',
            url: (payload) => `/org.gocom.bps.wfclient.agent.business.addAgent.addAgent.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.bps.wfclient.agent.business.addAgent.addAgent_params','description':'org.gocom.bps.wfclient.agent.business.addAgent.addAgent_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.bps.wfclient.agent.business.addAgent.addAgent_params'}}],
        },
        [agent.deleteAgent.method] : {
            summary: 'deleteAgent',
            method: 'post',
            url: (payload) => `/org.gocom.bps.wfclient.agent.business.maintainAgent.deleteAgent.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.bps.wfclient.agent.business.maintainAgent.deleteAgent_params','description':'org.gocom.bps.wfclient.agent.business.maintainAgent.deleteAgent_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.bps.wfclient.agent.business.maintainAgent.deleteAgent_params'}}],
        },
        [agent.detailAgent.method] : {
            summary: 'detailAgent',
            method: 'post',
            url: (payload) => `/org.gocom.bps.wfclient.agent.business.maintainAgent.detailAgent.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.bps.wfclient.agent.business.maintainAgent.detailAgent_params','description':'org.gocom.bps.wfclient.agent.business.maintainAgent.detailAgent_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.bps.wfclient.agent.business.maintainAgent.detailAgent_params'}}],
        },
        [agent.getProActInfo.method] : {
            summary: 'getProActInfo',
            method: 'post',
            url: (payload) => `/org.gocom.bps.wfclient.agent.business.queryAgent.getProActInfo.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.bps.wfclient.agent.business.queryAgent.getProActInfo_params','description':'org.gocom.bps.wfclient.agent.business.queryAgent.getProActInfo_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.bps.wfclient.agent.business.queryAgent.getProActInfo_params'}}],
        },
        [agent.modifyAgent.method] : {
            summary: 'modifyAgent',
            method: 'post',
            url: (payload) => `/org.gocom.bps.wfclient.agent.business.maintainAgent.modifyAgent.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.bps.wfclient.agent.business.maintainAgent.modifyAgent_params','description':'org.gocom.bps.wfclient.agent.business.maintainAgent.modifyAgent_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.bps.wfclient.agent.business.maintainAgent.modifyAgent_params'}}],
        },
        [agent.queryAgent.method] : {
            summary: 'queryAgent',
            method: 'post',
            url: (payload) => `/org.gocom.bps.wfclient.agent.business.queryAgent.queryAgent.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.bps.wfclient.agent.business.queryAgent.queryAgent_params','description':'org.gocom.bps.wfclient.agent.business.queryAgent.queryAgent_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.bps.wfclient.agent.business.queryAgent.queryAgent_params'}}],
        },
        [agent.queryAgentInfo.method] : {
            summary: 'queryAgentInfo',
            method: 'post',
            url: (payload) => `/org.gocom.bps.wfclient.agent.business.queryAgent.queryAgentInfo.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.bps.wfclient.agent.business.queryAgent.queryAgentInfo_params','description':'org.gocom.bps.wfclient.agent.business.queryAgent.queryAgentInfo_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.bps.wfclient.agent.business.queryAgent.queryAgentInfo_params'}}],
        },
        [agent.queryMyAgent.method] : {
            summary: 'queryMyAgent',
            method: 'post',
            url: (payload) => `/org.gocom.bps.wfclient.agent.business.queryAgent.queryMyAgent.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.bps.wfclient.agent.business.queryAgent.queryMyAgent_params','description':'org.gocom.bps.wfclient.agent.business.queryAgent.queryMyAgent_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.bps.wfclient.agent.business.queryAgent.queryMyAgent_params'}}],
        },
        [agent.queryProActInfo.method] : {
            summary: 'queryProActInfo',
            method: 'post',
            url: (payload) => `/org.gocom.bps.wfclient.agent.business.queryAgent.queryProActInfo.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.bps.wfclient.agent.business.queryAgent.queryProActInfo_params','description':'org.gocom.bps.wfclient.agent.business.queryAgent.queryProActInfo_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.bps.wfclient.agent.business.queryAgent.queryProActInfo_params'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
