//This file is automatically generated

// authForParty

import { authForParty } from '../controller';
export default {
    actions: {
        [authForParty.storePartyAuth.method] : {
            summary: 'storePartyAuth',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.authForParty.storePartyAuth.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.authForParty.storePartyAuth_params','description':'org.gocom.components.coframe.org.authForParty.storePartyAuth_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.authForParty.storePartyAuth_params'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
