//This file is automatically generated

// DictManager

import { DictManager } from '../controller';
export default {
    actions: {
        [DictManager.exportDict.method] : {
            summary: 'exportDict',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.dict.DictManager.exportDict.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.dict.DictManager.exportDict_params','description':'org.gocom.components.coframe.dict.DictManager.exportDict_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.dict.DictManager.exportDict_params'}}],
        },
        [DictManager.importDict.method] : {
            summary: 'importDict',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.dict.DictManager.importDict.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.dict.DictManager.importDict_params','description':'org.gocom.components.coframe.dict.DictManager.importDict_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.dict.DictManager.importDict_params'}}],
        },
        [DictManager.queryDict.method] : {
            summary: 'queryDict',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.dict.DictManager.queryDict.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.dict.DictManager.queryDict_params','description':'org.gocom.components.coframe.dict.DictManager.queryDict_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.dict.DictManager.queryDict_params'}}],
        },
        [DictManager.queryDictType.method] : {
            summary: 'queryDictType',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.dict.DictManager.queryDictType.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.dict.DictManager.queryDictType_params','description':'org.gocom.components.coframe.dict.DictManager.queryDictType_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.dict.DictManager.queryDictType_params'}}],
        },
        [DictManager.refreshDictCache.method] : {
            summary: 'refreshDictCache',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.dict.DictManager.refreshDictCache.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.dict.DictManager.refreshDictCache_params','description':'org.gocom.components.coframe.dict.DictManager.refreshDictCache_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.dict.DictManager.refreshDictCache_params'}}],
        },
        [DictManager.removeDict.method] : {
            summary: 'removeDict',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.dict.DictManager.removeDict.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.dict.DictManager.removeDict_params','description':'org.gocom.components.coframe.dict.DictManager.removeDict_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.dict.DictManager.removeDict_params'}}],
        },
        [DictManager.removeDictType.method] : {
            summary: 'removeDictType',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.dict.DictManager.removeDictType.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.dict.DictManager.removeDictType_params','description':'org.gocom.components.coframe.dict.DictManager.removeDictType_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.dict.DictManager.removeDictType_params'}}],
        },
        [DictManager.removeDictTypeCascade.method] : {
            summary: 'removeDictTypeCascade',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.dict.DictManager.removeDictTypeCascade.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.dict.DictManager.removeDictTypeCascade_params','description':'org.gocom.components.coframe.dict.DictManager.removeDictTypeCascade_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.dict.DictManager.removeDictTypeCascade_params'}}],
        },
        [DictManager.saveDict.method] : {
            summary: 'saveDict',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.dict.DictManager.saveDict.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.dict.DictManager.saveDict_params','description':'org.gocom.components.coframe.dict.DictManager.saveDict_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.dict.DictManager.saveDict_params'}}],
        },
        [DictManager.saveDictType.method] : {
            summary: 'saveDictType',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.dict.DictManager.saveDictType.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.dict.DictManager.saveDictType_params','description':'org.gocom.components.coframe.dict.DictManager.saveDictType_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.dict.DictManager.saveDictType_params'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
