//This file is automatically generated

// empgroup

import { empgroup } from '../controller';
export default {
    actions: {
        [empgroup.addEmpgroup.method] : {
            summary: 'addEmpgroup',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.empgroup.addEmpgroup.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.empgroup.addEmpgroup_params','description':'org.gocom.components.coframe.org.empgroup.addEmpgroup_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.empgroup.addEmpgroup_params'}}],
        },
        [empgroup.deleteEmpgroup.method] : {
            summary: 'deleteEmpgroup',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.empgroup.deleteEmpgroup.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.empgroup.deleteEmpgroup_params','description':'org.gocom.components.coframe.org.empgroup.deleteEmpgroup_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.empgroup.deleteEmpgroup_params'}}],
        },
        [empgroup.queryEmpInGroup.method] : {
            summary: 'queryEmpInGroup',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.empgroup.queryEmpInGroup.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.empgroup.queryEmpInGroup_params','description':'org.gocom.components.coframe.org.empgroup.queryEmpInGroup_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.empgroup.queryEmpInGroup_params'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
