//This file is automatically generated

// employeeAuth

import { employee } from '../controller';
export default {
    actions: {
        [employee.QueryEmpAllowAddInGroup.method] : {
            summary: 'QueryEmpAllowAddInGroup',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.employee.QueryEmpAllowAddInGroup.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.employee.QueryEmpAllowAddInGroup_params','description':'org.gocom.components.coframe.org.employee.QueryEmpAllowAddInGroup_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.employee.QueryEmpAllowAddInGroup_params'}}],
        },
        [employee.addEmployee.method] : {
            summary: 'addEmployee',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.employee.addEmployee.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.employee.addEmployee_params','description':'org.gocom.components.coframe.org.employee.addEmployee_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.employee.addEmployee_params'}}],
        },
        [employee.deleteEmployee.method] : {
            summary: 'deleteEmployee',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.employee.deleteEmployee.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.employee.deleteEmployee_params','description':'org.gocom.components.coframe.org.employee.deleteEmployee_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.employee.deleteEmployee_params'}}],
        },
        [employee.getEmpAuthorizedRoles.method] : {
            summary: 'getEmpAuthorizedRoles',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.employeeAuth.getEmpAuthorizedRoles.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.employeeAuth.getEmpAuthorizedRoles_params','description':'org.gocom.components.coframe.org.employeeAuth.getEmpAuthorizedRoles_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.employeeAuth.getEmpAuthorizedRoles_params'}}],
        },
        [employee.getEmpManagedRoles.method] : {
            summary: 'getEmpManagedRoles',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.employeeAuth.getEmpManagedRoles.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.employeeAuth.getEmpManagedRoles_params','description':'org.gocom.components.coframe.org.employeeAuth.getEmpManagedRoles_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.employeeAuth.getEmpManagedRoles_params'}}],
        },
        [employee.getEmpUnmanagedRoles.method] : {
            summary: 'getEmpUnmanagedRoles',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.employeeAuth.getEmpUnmanagedRoles.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.employeeAuth.getEmpUnmanagedRoles_params','description':'org.gocom.components.coframe.org.employeeAuth.getEmpUnmanagedRoles_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.employeeAuth.getEmpUnmanagedRoles_params'}}],
        },
        [employee.getEmployee.method] : {
            summary: 'getEmployee',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.employee.getEmployee.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.employee.getEmployee_params','description':'org.gocom.components.coframe.org.employee.getEmployee_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.employee.getEmployee_params'}}],
        },
        [employee.getEmployeeAuth.method] : {
            summary: 'getEmployeeAuth',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.employeeAuth.getEmployeeAuth.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.employeeAuth.getEmployeeAuth_params','description':'org.gocom.components.coframe.org.employeeAuth.getEmployeeAuth_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.employeeAuth.getEmployeeAuth_params'}}],
        },
        [employee.queryEmpAllowAddInPosition.method] : {
            summary: 'queryEmpAllowAddInPosition',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.employee.queryEmpAllowAddInPosition.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.employee.queryEmpAllowAddInPosition_params','description':'org.gocom.components.coframe.org.employee.queryEmpAllowAddInPosition_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.employee.queryEmpAllowAddInPosition_params'}}],
        },
        [employee.queryEmpInPosition.method] : {
            summary: 'queryEmpInPosition',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.employee.queryEmpInPosition.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.employee.queryEmpInPosition_params','description':'org.gocom.components.coframe.org.employee.queryEmpInPosition_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.employee.queryEmpInPosition_params'}}],
        },
        [employee.queryEmpUsers.method] : {
            summary: 'queryEmpUsers',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.employee.queryEmpUsers.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.employee.queryEmpUsers_params','description':'org.gocom.components.coframe.org.employee.queryEmpUsers_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.employee.queryEmpUsers_params'}}],
        },
        [employee.queryEmployee.method] : {
            summary: 'queryEmployee',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.employee.queryEmployee.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.employee.queryEmployee_params','description':'org.gocom.components.coframe.org.employee.queryEmployee_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.employee.queryEmployee_params'}}],
        },
        [employee.updateEmpDetaiInfo.method] : {
            summary: 'updateEmpDetaiInfo',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.employee.updateEmpDetaiInfo.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.employee.updateEmpDetaiInfo_params','description':'org.gocom.components.coframe.org.employee.updateEmpDetaiInfo_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.employee.updateEmpDetaiInfo_params'}}],
        },
        [employee.updateEmployee.method] : {
            summary: 'updateEmployee',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.employee.updateEmployee.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.employee.updateEmployee_params','description':'org.gocom.components.coframe.org.employee.updateEmployee_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.employee.updateEmployee_params'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
