//This file is automatically generated

// employeeAuth

import { employeeAuth } from '../controller';
export default {
    actions: {
        [employeeAuth.getEmpAuthorizedRoles.method] : {
            summary: 'getEmpAuthorizedRoles',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.employeeAuth.getEmpAuthorizedRoles.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.employeeAuth.getEmpAuthorizedRoles_params','description':'org.gocom.components.coframe.org.employeeAuth.getEmpAuthorizedRoles_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.employeeAuth.getEmpAuthorizedRoles_params'}}],
        },
        [employeeAuth.getEmpManagedRoles.method] : {
            summary: 'getEmpManagedRoles',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.employeeAuth.getEmpManagedRoles.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.employeeAuth.getEmpManagedRoles_params','description':'org.gocom.components.coframe.org.employeeAuth.getEmpManagedRoles_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.employeeAuth.getEmpManagedRoles_params'}}],
        },
        [employeeAuth.getEmpUnmanagedRoles.method] : {
            summary: 'getEmpUnmanagedRoles',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.employeeAuth.getEmpUnmanagedRoles.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.employeeAuth.getEmpUnmanagedRoles_params','description':'org.gocom.components.coframe.org.employeeAuth.getEmpUnmanagedRoles_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.employeeAuth.getEmpUnmanagedRoles_params'}}],
        },
        [employeeAuth.getEmployeeAuth.method] : {
            summary: 'getEmployeeAuth',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.employeeAuth.getEmployeeAuth.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.employeeAuth.getEmployeeAuth_params','description':'org.gocom.components.coframe.org.employeeAuth.getEmployeeAuth_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.employeeAuth.getEmployeeAuth_params'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
