//This file is automatically generated

// rule

import { entity } from '../controller';
export default {
    actions: {
        [entity.delRules.method] : {
            summary: 'delRules',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.entityauth.rule.delRules.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.entityauth.rule.delRules_params','description':'org.gocom.components.coframe.entityauth.rule.delRules_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.entityauth.rule.delRules_params'}}],
        },
        [entity.getConValues.method] : {
            summary: 'getConValues',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.entityauth.rule.getConValues.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.entityauth.rule.getConValues_params','description':'org.gocom.components.coframe.entityauth.rule.getConValues_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.entityauth.rule.getConValues_params'}}],
        },
        [entity.getEntityCapRules.method] : {
            summary: 'getEntityCapRules',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.entityauth.rule.getEntityCapRules.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.entityauth.rule.getEntityCapRules_params','description':'org.gocom.components.coframe.entityauth.rule.getEntityCapRules_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.entityauth.rule.getEntityCapRules_params'}}],
        },
        [entity.getEntityInfoPropertie.method] : {
            summary: 'getEntityInfoPropertie',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.entityauth.entity.getEntityInfoPropertie.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.entityauth.entity.getEntityInfoPropertie_params','description':'org.gocom.components.coframe.entityauth.entity.getEntityInfoPropertie_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.entityauth.entity.getEntityInfoPropertie_params'}}],
        },
        [entity.getEntityInfoProperties.method] : {
            summary: 'getEntityInfoProperties',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.entityauth.entity.getEntityInfoProperties.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.entityauth.entity.getEntityInfoProperties_params','description':'org.gocom.components.coframe.entityauth.entity.getEntityInfoProperties_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.entityauth.entity.getEntityInfoProperties_params'}}],
        },
        [entity.getEntityInfos.method] : {
            summary: 'getEntityInfos',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.entityauth.entity.getEntityInfos.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.entityauth.entity.getEntityInfos_params','description':'org.gocom.components.coframe.entityauth.entity.getEntityInfos_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.entityauth.entity.getEntityInfos_params'}}],
        },
        [entity.getRightValues.method] : {
            summary: 'getRightValues',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.entityauth.rule.getRightValues.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.entityauth.rule.getRightValues_params','description':'org.gocom.components.coframe.entityauth.rule.getRightValues_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.entityauth.rule.getRightValues_params'}}],
        },
        [entity.getRuleCondition.method] : {
            summary: 'getRuleCondition',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.entityauth.rule.getRuleCondition.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.entityauth.rule.getRuleCondition_params','description':'org.gocom.components.coframe.entityauth.rule.getRuleCondition_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.entityauth.rule.getRuleCondition_params'}}],
        },
        [entity.saveRule.method] : {
            summary: 'saveRule',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.entityauth.rule.saveRule.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.entityauth.rule.saveRule_params','description':'org.gocom.components.coframe.entityauth.rule.saveRule_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.entityauth.rule.saveRule_params'}}],
        },
        [entity.storePartyAuth.method] : {
            summary: 'storePartyAuth',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.entityauth.rule.storePartyAuth.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.entityauth.rule.storePartyAuth_params','description':'org.gocom.components.coframe.entityauth.rule.storePartyAuth_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.entityauth.rule.storePartyAuth_params'}}],
        },
        [entity.updateRule.method] : {
            summary: 'updateRule',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.entityauth.rule.updateRule.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.entityauth.rule.updateRule_params','description':'org.gocom.components.coframe.entityauth.rule.updateRule_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.entityauth.rule.updateRule_params'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
