//This file is automatically generated

// fileupload

import { fileupload } from '../controller';
export default {
    actions: {
        [fileupload.loadFiles.method] : {
            summary: 'loadFiles',
            method: 'post',
            url: (payload) => `/com.primeton.components.web.fileupload.fileupload.loadFiles.biz.ext`,
            parameters: [{'in':'body','name':'com.primeton.components.web.fileupload.fileupload.loadFiles_params','description':'com.primeton.components.web.fileupload.fileupload.loadFiles_params','required':true,'schema':{'$ref':'#/definitions/com.primeton.components.web.fileupload.fileupload.loadFiles_params'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
