//This file is automatically generated

// FunctionManager

import { FunctionManager } from '../controller';
export default {
    actions: {
        [FunctionManager.getFunction.method] : {
            summary: 'getFunction',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.framework.FunctionManager.getFunction.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.framework.FunctionManager.getFunction_params','description':'org.gocom.components.coframe.framework.FunctionManager.getFunction_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.framework.FunctionManager.getFunction_params'}}],
        },
        [FunctionManager.queryFunction.method] : {
            summary: 'queryFunction',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.framework.FunctionManager.queryFunction.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.framework.FunctionManager.queryFunction_params','description':'org.gocom.components.coframe.framework.FunctionManager.queryFunction_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.framework.FunctionManager.queryFunction_params'}}],
        },
        [FunctionManager.saveFunction.method] : {
            summary: 'saveFunction',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.framework.FunctionManager.saveFunction.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.framework.FunctionManager.saveFunction_params','description':'org.gocom.components.coframe.framework.FunctionManager.saveFunction_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.framework.FunctionManager.saveFunction_params'}}],
        },
        [FunctionManager.updateFunction.method] : {
            summary: 'updateFunction',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.framework.FunctionManager.updateFunction.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.framework.FunctionManager.updateFunction_params','description':'org.gocom.components.coframe.framework.FunctionManager.updateFunction_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.framework.FunctionManager.updateFunction_params'}}],
        },
        [FunctionManager.validateFunction.method] : {
            summary: 'validateFunction',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.framework.FunctionManager.validateFunction.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.framework.FunctionManager.validateFunction_params','description':'org.gocom.components.coframe.framework.FunctionManager.validateFunction_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.framework.FunctionManager.validateFunction_params'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
