//This file is automatically generated

// FuncGroupManager

import { FuncGroupManager } from '../controller';
export default {
    actions: {
        [FuncGroupManager.getFuncGroup.method] : {
            summary: 'getFuncGroup',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.framework.FuncGroupManager.getFuncGroup.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.framework.FuncGroupManager.getFuncGroup_params','description':'org.gocom.components.coframe.framework.FuncGroupManager.getFuncGroup_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.framework.FuncGroupManager.getFuncGroup_params'}}],
        },
        [FuncGroupManager.queryFuncGroup.method] : {
            summary: 'queryFuncGroup',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.framework.FuncGroupManager.queryFuncGroup.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.framework.FuncGroupManager.queryFuncGroup_params','description':'org.gocom.components.coframe.framework.FuncGroupManager.queryFuncGroup_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.framework.FuncGroupManager.queryFuncGroup_params'}}],
        },
        [FuncGroupManager.querySubFuncGroup.method] : {
            summary: 'querySubFuncGroup',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.framework.FuncGroupManager.querySubFuncGroup.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.framework.FuncGroupManager.querySubFuncGroup_params','description':'org.gocom.components.coframe.framework.FuncGroupManager.querySubFuncGroup_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.framework.FuncGroupManager.querySubFuncGroup_params'}}],
        },
        [FuncGroupManager.saveFuncGroup.method] : {
            summary: 'saveFuncGroup',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.framework.FuncGroupManager.saveFuncGroup.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.framework.FuncGroupManager.saveFuncGroup_params','description':'org.gocom.components.coframe.framework.FuncGroupManager.saveFuncGroup_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.framework.FuncGroupManager.saveFuncGroup_params'}}],
        },
        [FuncGroupManager.saveSubFuncGroup.method] : {
            summary: 'saveSubFuncGroup',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.framework.FuncGroupManager.saveSubFuncGroup.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.framework.FuncGroupManager.saveSubFuncGroup_params','description':'org.gocom.components.coframe.framework.FuncGroupManager.saveSubFuncGroup_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.framework.FuncGroupManager.saveSubFuncGroup_params'}}],
        },
        [FuncGroupManager.updateFuncGroup.method] : {
            summary: 'updateFuncGroup',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.framework.FuncGroupManager.updateFuncGroup.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.framework.FuncGroupManager.updateFuncGroup_params','description':'org.gocom.components.coframe.framework.FuncGroupManager.updateFuncGroup_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.framework.FuncGroupManager.updateFuncGroup_params'}}],
        },
        [FuncGroupManager.updateFuncGroupRelation.method] : {
            summary: 'updateFuncGroupRelation',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.framework.FuncGroupManager.updateFuncGroupRelation.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.framework.FuncGroupManager.updateFuncGroupRelation_params','description':'org.gocom.components.coframe.framework.FuncGroupManager.updateFuncGroupRelation_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.framework.FuncGroupManager.updateFuncGroupRelation_params'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
