//This file is automatically generated

// groupposi

import { groupposi } from '../controller';
export default {
    actions: {
        [groupposi.addGroupposi.method] : {
            summary: 'addGroupposi',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.groupposi.addGroupposi.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.groupposi.addGroupposi_params','description':'org.gocom.components.coframe.org.groupposi.addGroupposi_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.groupposi.addGroupposi_params'}}],
        },
        [groupposi.queryGroupposi.method] : {
            summary: 'queryGroupposi',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.groupposi.queryGroupposi.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.groupposi.queryGroupposi_params','description':'org.gocom.components.coframe.org.groupposi.queryGroupposi_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.groupposi.queryGroupposi_params'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
