//This file is automatically generated

// groupselect

import { groupselect } from '../controller';
export default {
    actions: {
        [groupselect.groupList.method] : {
            summary: 'groupList',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.participantselect.groupselect.groupList.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.participantselect.groupselect.groupList_params','description':'org.gocom.components.coframe.participantselect.groupselect.groupList_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.participantselect.groupselect.groupList_params'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
