//This file is automatically generated

// userselect

import { group } from '../controller';
export default {
    actions: {
        [group.addEmpgroup.method] : {
            summary: 'addEmpgroup',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.empgroup.addEmpgroup.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.empgroup.addEmpgroup_params','description':'org.gocom.components.coframe.org.empgroup.addEmpgroup_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.empgroup.addEmpgroup_params'}}],
        },
        [group.addGroup.method] : {
            summary: 'addGroup',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.group.addGroup.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.group.addGroup_params','description':'org.gocom.components.coframe.org.group.addGroup_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.group.addGroup_params'}}],
        },
        [group.addGroupposi.method] : {
            summary: 'addGroupposi',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.groupposi.addGroupposi.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.groupposi.addGroupposi_params','description':'org.gocom.components.coframe.org.groupposi.addGroupposi_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.groupposi.addGroupposi_params'}}],
        },
        [group.copyNode.method] : {
            summary: 'copyNode',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.group.copyNode.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.group.copyNode_params','description':'org.gocom.components.coframe.org.group.copyNode_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.group.copyNode_params'}}],
        },
        [group.deleteCurrentNode.method] : {
            summary: 'deleteCurrentNode',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.group.deleteCurrentNode.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.group.deleteCurrentNode_params','description':'org.gocom.components.coframe.org.group.deleteCurrentNode_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.group.deleteCurrentNode_params'}}],
        },
        [group.deleteEmpgroup.method] : {
            summary: 'deleteEmpgroup',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.empgroup.deleteEmpgroup.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.empgroup.deleteEmpgroup_params','description':'org.gocom.components.coframe.org.empgroup.deleteEmpgroup_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.empgroup.deleteEmpgroup_params'}}],
        },
        [group.deleteNode.method] : {
            summary: 'deleteNode',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.group.deleteNode.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.group.deleteNode_params','description':'org.gocom.components.coframe.org.group.deleteNode_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.group.deleteNode_params'}}],
        },
        [group.deleteNodes.method] : {
            summary: 'deleteNodes',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.group.deleteNodes.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.group.deleteNodes_params','description':'org.gocom.components.coframe.org.group.deleteNodes_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.group.deleteNodes_params'}}],
        },
        [group.getGroupAuth.method] : {
            summary: 'getGroupAuth',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.groupAuth.getGroupAuth.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.groupAuth.getGroupAuth_params','description':'org.gocom.components.coframe.org.groupAuth.getGroupAuth_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.groupAuth.getGroupAuth_params'}}],
        },
        [group.getGroupWithParent.method] : {
            summary: 'getGroupWithParent',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.group.getGroupWithParent.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.group.getGroupWithParent_params','description':'org.gocom.components.coframe.org.group.getGroupWithParent_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.group.getGroupWithParent_params'}}],
        },
        [group.getManagedGroupByRoleId.method] : {
            summary: 'getManagedGroupByRoleId',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.groupAuth.getManagedGroupByRoleId.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.groupAuth.getManagedGroupByRoleId_params','description':'org.gocom.components.coframe.org.groupAuth.getManagedGroupByRoleId_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.groupAuth.getManagedGroupByRoleId_params'}}],
        },
        [group.groupList.method] : {
            summary: 'groupList',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.participantselect.groupselect.groupList.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.participantselect.groupselect.groupList_params','description':'org.gocom.components.coframe.participantselect.groupselect.groupList_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.participantselect.groupselect.groupList_params'}}],
        },
        [group.groupUserList.method] : {
            summary: 'groupUserList',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.participantselect.userselect.groupUserList.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.participantselect.userselect.groupUserList_params','description':'org.gocom.components.coframe.participantselect.userselect.groupUserList_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.participantselect.userselect.groupUserList_params'}}],
        },
        [group.moveNode.method] : {
            summary: 'moveNode',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.group.moveNode.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.group.moveNode_params','description':'org.gocom.components.coframe.org.group.moveNode_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.group.moveNode_params'}}],
        },
        [group.queryAllChildNodes.method] : {
            summary: 'queryAllChildNodes',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.group.queryAllChildNodes.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.group.queryAllChildNodes_params','description':'org.gocom.components.coframe.org.group.queryAllChildNodes_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.group.queryAllChildNodes_params'}}],
        },
        [group.queryEmpInGroup.method] : {
            summary: 'queryEmpInGroup',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.empgroup.queryEmpInGroup.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.empgroup.queryEmpInGroup_params','description':'org.gocom.components.coframe.org.empgroup.queryEmpInGroup_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.empgroup.queryEmpInGroup_params'}}],
        },
        [group.queryGroup.method] : {
            summary: 'queryGroup',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.group.queryGroup.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.group.queryGroup_params','description':'org.gocom.components.coframe.org.group.queryGroup_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.group.queryGroup_params'}}],
        },
        [group.queryGroupposi.method] : {
            summary: 'queryGroupposi',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.groupposi.queryGroupposi.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.groupposi.queryGroupposi_params','description':'org.gocom.components.coframe.org.groupposi.queryGroupposi_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.groupposi.queryGroupposi_params'}}],
        },
        [group.querySubGroup.method] : {
            summary: 'querySubGroup',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.group.querySubGroup.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.group.querySubGroup_params','description':'org.gocom.components.coframe.org.group.querySubGroup_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.group.querySubGroup_params'}}],
        },
        [group.queryTreeChildNodes.method] : {
            summary: 'queryTreeChildNodes',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.group.queryTreeChildNodes.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.group.queryTreeChildNodes_params','description':'org.gocom.components.coframe.org.group.queryTreeChildNodes_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.group.queryTreeChildNodes_params'}}],
        },
        [group.saveGroupAuth.method] : {
            summary: 'saveGroupAuth',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.groupAuth.saveGroupAuth.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.groupAuth.saveGroupAuth_params','description':'org.gocom.components.coframe.org.groupAuth.saveGroupAuth_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.groupAuth.saveGroupAuth_params'}}],
        },
        [group.updateGroup.method] : {
            summary: 'updateGroup',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.group.updateGroup.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.group.updateGroup_params','description':'org.gocom.components.coframe.org.group.updateGroup_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.group.updateGroup_params'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
