//This file is automatically generated

// ipRuleComponent

import { ipRuleComponent } from '../controller';
export default {
    actions: {
        [ipRuleComponent.deleteAccessRules.method] : {
            summary: 'deleteAccessRules',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.policy.ipRuleComponent.deleteAccessRules.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.policy.ipRuleComponent.deleteAccessRules_params','description':'org.gocom.components.coframe.policy.ipRuleComponent.deleteAccessRules_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.policy.ipRuleComponent.deleteAccessRules_params'}}],
        },
        [ipRuleComponent.editAccessRules.method] : {
            summary: 'editAccessRules',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.policy.ipRuleComponent.editAccessRules.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.policy.ipRuleComponent.editAccessRules_params','description':'org.gocom.components.coframe.policy.ipRuleComponent.editAccessRules_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.policy.ipRuleComponent.editAccessRules_params'}}],
        },
        [ipRuleComponent.getAccessRules.method] : {
            summary: 'getAccessRules',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.policy.ipRuleComponent.getAccessRules.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.policy.ipRuleComponent.getAccessRules_params','description':'org.gocom.components.coframe.policy.ipRuleComponent.getAccessRules_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.policy.ipRuleComponent.getAccessRules_params'}}],
        },
        [ipRuleComponent.verificationIp.method] : {
            summary: 'verificationIp',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.policy.ipRuleComponent.verificationIp.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.policy.ipRuleComponent.verificationIp_params','description':'org.gocom.components.coframe.policy.ipRuleComponent.verificationIp_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.policy.ipRuleComponent.verificationIp_params'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
