//This file is automatically generated

// ManageableRes

import { ManageableRes } from '../controller';
export default {
    actions: {
        [ManageableRes.getManageableGroup.method] : {
            summary: 'getManageableGroup',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.auth.partyauth.ManageableRes.getManageableGroup.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.auth.partyauth.ManageableRes.getManageableGroup_params','description':'org.gocom.components.coframe.auth.partyauth.ManageableRes.getManageableGroup_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.auth.partyauth.ManageableRes.getManageableGroup_params'}}],
        },
        [ManageableRes.getManageableOrg.method] : {
            summary: 'getManageableOrg',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.auth.partyauth.ManageableRes.getManageableOrg.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.auth.partyauth.ManageableRes.getManageableOrg_params','description':'org.gocom.components.coframe.auth.partyauth.ManageableRes.getManageableOrg_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.auth.partyauth.ManageableRes.getManageableOrg_params'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
