//This file is automatically generated

// MenuManager

import { MenuManager } from '../controller';
export default {
    actions: {
        [MenuManager.deleteMenu.method] : {
            summary: 'deleteMenu',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.framework.MenuManager.deleteMenu.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.framework.MenuManager.deleteMenu_params','description':'org.gocom.components.coframe.framework.MenuManager.deleteMenu_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.framework.MenuManager.deleteMenu_params'}}],
        },
        [MenuManager.deleteMenuNodes.method] : {
            summary: 'deleteMenuNodes',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.framework.MenuManager.deleteMenuNodes.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.framework.MenuManager.deleteMenuNodes_params','description':'org.gocom.components.coframe.framework.MenuManager.deleteMenuNodes_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.framework.MenuManager.deleteMenuNodes_params'}}],
        },
        [MenuManager.deleteMenus.method] : {
            summary: 'deleteMenus',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.framework.MenuManager.deleteMenus.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.framework.MenuManager.deleteMenus_params','description':'org.gocom.components.coframe.framework.MenuManager.deleteMenus_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.framework.MenuManager.deleteMenus_params'}}],
        },
        [MenuManager.getMenu.method] : {
            summary: 'getMenu',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.framework.MenuManager.getMenu.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.framework.MenuManager.getMenu_params','description':'org.gocom.components.coframe.framework.MenuManager.getMenu_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.framework.MenuManager.getMenu_params'}}],
        },
        [MenuManager.queryMenu.method] : {
            summary: 'queryMenu',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.framework.MenuManager.queryMenu.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.framework.MenuManager.queryMenu_params','description':'org.gocom.components.coframe.framework.MenuManager.queryMenu_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.framework.MenuManager.queryMenu_params'}}],
        },
        [MenuManager.queryMenuTreeNode.method] : {
            summary: 'queryMenuTreeNode',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.framework.MenuManager.queryMenuTreeNode.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.framework.MenuManager.queryMenuTreeNode_params','description':'org.gocom.components.coframe.framework.MenuManager.queryMenuTreeNode_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.framework.MenuManager.queryMenuTreeNode_params'}}],
        },
        [MenuManager.saveMenu.method] : {
            summary: 'saveMenu',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.framework.MenuManager.saveMenu.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.framework.MenuManager.saveMenu_params','description':'org.gocom.components.coframe.framework.MenuManager.saveMenu_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.framework.MenuManager.saveMenu_params'}}],
        },
        [MenuManager.updateMenu.method] : {
            summary: 'updateMenu',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.framework.MenuManager.updateMenu.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.framework.MenuManager.updateMenu_params','description':'org.gocom.components.coframe.framework.MenuManager.updateMenu_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.framework.MenuManager.updateMenu_params'}}],
        },
        [MenuManager.updateMenuRelation.method] : {
            summary: 'updateMenuRelation',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.framework.MenuManager.updateMenuRelation.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.framework.MenuManager.updateMenuRelation_params','description':'org.gocom.components.coframe.framework.MenuManager.updateMenuRelation_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.framework.MenuManager.updateMenuRelation_params'}}],
        },
        [MenuManager.validateMenu.method] : {
            summary: 'validateMenu',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.framework.MenuManager.validateMenu.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.framework.MenuManager.validateMenu_params','description':'org.gocom.components.coframe.framework.MenuManager.validateMenu_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.framework.MenuManager.validateMenu_params'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
