//This file is automatically generated

// organizationAuth

import { organization } from '../controller';
export default {
    actions: {
        [organization.addOrg.method] : {
            summary: 'addOrg',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.organization.addOrg.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.organization.addOrg_params','description':'org.gocom.components.coframe.org.organization.addOrg_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.organization.addOrg_params'}}],
        },
        [organization.copyNode.method] : {
            summary: 'copyNode',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.organization.copyNode.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.organization.copyNode_params','description':'org.gocom.components.coframe.org.organization.copyNode_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.organization.copyNode_params'}}],
        },
        [organization.deleteCurrentNode.method] : {
            summary: 'deleteCurrentNode',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.organization.deleteCurrentNode.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.organization.deleteCurrentNode_params','description':'org.gocom.components.coframe.org.organization.deleteCurrentNode_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.organization.deleteCurrentNode_params'}}],
        },
        [organization.deleteNode.method] : {
            summary: 'deleteNode',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.organization.deleteNode.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.organization.deleteNode_params','description':'org.gocom.components.coframe.org.organization.deleteNode_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.organization.deleteNode_params'}}],
        },
        [organization.deleteNodes.method] : {
            summary: 'deleteNodes',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.organization.deleteNodes.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.organization.deleteNodes_params','description':'org.gocom.components.coframe.org.organization.deleteNodes_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.organization.deleteNodes_params'}}],
        },
        [organization.deleteOrg.method] : {
            summary: 'deleteOrg',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.organization.deleteOrg.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.organization.deleteOrg_params','description':'org.gocom.components.coframe.org.organization.deleteOrg_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.organization.deleteOrg_params'}}],
        },
        [organization.getManagerOrgByRole.method] : {
            summary: 'getManagerOrgByRole',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.organizationAuth.getManagerOrgByRole.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.organizationAuth.getManagerOrgByRole_params','description':'org.gocom.components.coframe.org.organizationAuth.getManagerOrgByRole_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.organizationAuth.getManagerOrgByRole_params'}}],
        },
        [organization.getOrgStaticTree.method] : {
            summary: 'getOrgStaticTree',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.organization.getOrgStaticTree.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.organization.getOrgStaticTree_params','description':'org.gocom.components.coframe.org.organization.getOrgStaticTree_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.organization.getOrgStaticTree_params'}}],
        },
        [organization.getOrgWithParent.method] : {
            summary: 'getOrgWithParent',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.organization.getOrgWithParent.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.organization.getOrgWithParent_params','description':'org.gocom.components.coframe.org.organization.getOrgWithParent_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.organization.getOrgWithParent_params'}}],
        },
        [organization.getOrganizationAuth.method] : {
            summary: 'getOrganizationAuth',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.organizationAuth.getOrganizationAuth.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.organizationAuth.getOrganizationAuth_params','description':'org.gocom.components.coframe.org.organizationAuth.getOrganizationAuth_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.organizationAuth.getOrganizationAuth_params'}}],
        },
        [organization.moveNode.method] : {
            summary: 'moveNode',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.organization.moveNode.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.organization.moveNode_params','description':'org.gocom.components.coframe.org.organization.moveNode_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.organization.moveNode_params'}}],
        },
        [organization.queryAll.method] : {
            summary: 'queryAll',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.organization.queryAll.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.organization.queryAll_params','description':'org.gocom.components.coframe.org.organization.queryAll_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.organization.queryAll_params'}}],
        },
        [organization.queryAllChildNodes.method] : {
            summary: 'queryAllChildNodes',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.organization.queryAllChildNodes.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.organization.queryAllChildNodes_params','description':'org.gocom.components.coframe.org.organization.queryAllChildNodes_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.organization.queryAllChildNodes_params'}}],
        },
        [organization.queryOrg.method] : {
            summary: 'queryOrg',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.organization.queryOrg.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.organization.queryOrg_params','description':'org.gocom.components.coframe.org.organization.queryOrg_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.organization.queryOrg_params'}}],
        },
        [organization.queryTreeChildNodes.method] : {
            summary: 'queryTreeChildNodes',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.organization.queryTreeChildNodes.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.organization.queryTreeChildNodes_params','description':'org.gocom.components.coframe.org.organization.queryTreeChildNodes_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.organization.queryTreeChildNodes_params'}}],
        },
        [organization.saveOrganizationAuth.method] : {
            summary: 'saveOrganizationAuth',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.organizationAuth.saveOrganizationAuth.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.organizationAuth.saveOrganizationAuth_params','description':'org.gocom.components.coframe.org.organizationAuth.saveOrganizationAuth_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.organizationAuth.saveOrganizationAuth_params'}}],
        },
        [organization.updateOrg.method] : {
            summary: 'updateOrg',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.organization.updateOrg.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.organization.updateOrg_params','description':'org.gocom.components.coframe.org.organization.updateOrg_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.organization.updateOrg_params'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
