//This file is automatically generated

// organizationAuth

import { organizationAuth } from '../controller';
export default {
    actions: {
        [organizationAuth.getManagerOrgByRole.method] : {
            summary: 'getManagerOrgByRole',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.organizationAuth.getManagerOrgByRole.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.organizationAuth.getManagerOrgByRole_params','description':'org.gocom.components.coframe.org.organizationAuth.getManagerOrgByRole_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.organizationAuth.getManagerOrgByRole_params'}}],
        },
        [organizationAuth.getOrganizationAuth.method] : {
            summary: 'getOrganizationAuth',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.organizationAuth.getOrganizationAuth.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.organizationAuth.getOrganizationAuth_params','description':'org.gocom.components.coframe.org.organizationAuth.getOrganizationAuth_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.organizationAuth.getOrganizationAuth_params'}}],
        },
        [organizationAuth.saveOrganizationAuth.method] : {
            summary: 'saveOrganizationAuth',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.organizationAuth.saveOrganizationAuth.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.organizationAuth.saveOrganizationAuth_params','description':'org.gocom.components.coframe.org.organizationAuth.saveOrganizationAuth_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.organizationAuth.saveOrganizationAuth_params'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
