//This file is automatically generated

// partyauth

import { partyauth } from '../controller';
export default {
    actions: {
        [partyauth.addPartyAuth.method] : {
            summary: 'addPartyAuth',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.auth.partyauth.partyauth.addPartyAuth.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.auth.partyauth.partyauth.addPartyAuth_params','description':'org.gocom.components.coframe.auth.partyauth.partyauth.addPartyAuth_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.auth.partyauth.partyauth.addPartyAuth_params'}}],
        },
        [partyauth.deletePartyAuth.method] : {
            summary: 'deletePartyAuth',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.auth.partyauth.partyauth.deletePartyAuth.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.auth.partyauth.partyauth.deletePartyAuth_params','description':'org.gocom.components.coframe.auth.partyauth.partyauth.deletePartyAuth_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.auth.partyauth.partyauth.deletePartyAuth_params'}}],
        },
        [partyauth.getAuthorizedRoleList.method] : {
            summary: 'getAuthorizedRoleList',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.auth.partyauth.partyauth.getAuthorizedRoleList.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.auth.partyauth.partyauth.getAuthorizedRoleList_params','description':'org.gocom.components.coframe.auth.partyauth.partyauth.getAuthorizedRoleList_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.auth.partyauth.partyauth.getAuthorizedRoleList_params'}}],
        },
        [partyauth.getManageableGroup.method] : {
            summary: 'getManageableGroup',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.auth.partyauth.ManageableRes.getManageableGroup.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.auth.partyauth.ManageableRes.getManageableGroup_params','description':'org.gocom.components.coframe.auth.partyauth.ManageableRes.getManageableGroup_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.auth.partyauth.ManageableRes.getManageableGroup_params'}}],
        },
        [partyauth.getManageableOrg.method] : {
            summary: 'getManageableOrg',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.auth.partyauth.ManageableRes.getManageableOrg.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.auth.partyauth.ManageableRes.getManageableOrg_params','description':'org.gocom.components.coframe.auth.partyauth.ManageableRes.getManageableOrg_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.auth.partyauth.ManageableRes.getManageableOrg_params'}}],
        },
        [partyauth.getUnauthorizedRoleList.method] : {
            summary: 'getUnauthorizedRoleList',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.auth.partyauth.partyauth.getUnauthorizedRoleList.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.auth.partyauth.partyauth.getUnauthorizedRoleList_params','description':'org.gocom.components.coframe.auth.partyauth.partyauth.getUnauthorizedRoleList_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.auth.partyauth.partyauth.getUnauthorizedRoleList_params'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
