//This file is automatically generated

// positionAuth

import { positionAuth } from '../controller';
export default {
    actions: {
        [positionAuth.getPositionAuth.method] : {
            summary: 'getPositionAuth',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.org.positionAuth.getPositionAuth.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.org.positionAuth.getPositionAuth_params','description':'org.gocom.components.coframe.org.positionAuth.getPositionAuth_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.org.positionAuth.getPositionAuth_params'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
