//This file is automatically generated

// process

import { process } from '../controller';
export default {
    actions: {
        [process.commonQueryProcessInst.method] : {
            summary: 'commonQueryProcessInst',
            method: 'post',
            url: (payload) => `/org.gocom.bps.wfclient.process.myProcess.commonQueryProcessInst.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.bps.wfclient.process.myProcess.commonQueryProcessInst_params','description':'org.gocom.bps.wfclient.process.myProcess.commonQueryProcessInst_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.bps.wfclient.process.myProcess.commonQueryProcessInst_params'}}],
        },
        [process.createStartProcessInst.method] : {
            summary: 'createStartProcessInst',
            method: 'post',
            url: (payload) => `/org.gocom.bps.wfclient.process.processMgr.createStartProcessInst.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.bps.wfclient.process.processMgr.createStartProcessInst_params','description':'org.gocom.bps.wfclient.process.processMgr.createStartProcessInst_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.bps.wfclient.process.processMgr.createStartProcessInst_params'}}],
        },
        [process.getCatalogSubByUserid.method] : {
            summary: 'getCatalogSubByUserid',
            method: 'post',
            url: (payload) => `/org.gocom.bps.wfclient.process.processCatalogMgr.getCatalogSubByUserid.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.bps.wfclient.process.processCatalogMgr.getCatalogSubByUserid_params','description':'org.gocom.bps.wfclient.process.processCatalogMgr.getCatalogSubByUserid_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.bps.wfclient.process.processCatalogMgr.getCatalogSubByUserid_params'}}],
        },
        [process.getProcessCatalogs.method] : {
            summary: 'getProcessCatalogs',
            method: 'post',
            url: (payload) => `/org.gocom.bps.wfclient.process.processCatalogMgr.getProcessCatalogs.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.bps.wfclient.process.processCatalogMgr.getProcessCatalogs_params','description':'org.gocom.bps.wfclient.process.processCatalogMgr.getProcessCatalogs_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.bps.wfclient.process.processCatalogMgr.getProcessCatalogs_params'}}],
        },
        [process.queryMyProcess.method] : {
            summary: 'queryMyProcess',
            method: 'post',
            url: (payload) => `/org.gocom.bps.wfclient.process.myProcess.queryMyProcess.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.bps.wfclient.process.myProcess.queryMyProcess_params','description':'org.gocom.bps.wfclient.process.myProcess.queryMyProcess_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.bps.wfclient.process.myProcess.queryMyProcess_params'}}],
        },
        [process.queryProcess.method] : {
            summary: 'queryProcess',
            method: 'post',
            url: (payload) => `/org.gocom.bps.wfclient.process.myProcess.queryProcess.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.bps.wfclient.process.myProcess.queryProcess_params','description':'org.gocom.bps.wfclient.process.myProcess.queryProcess_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.bps.wfclient.process.myProcess.queryProcess_params'}}],
        },
        [process.queryPublishedProcessWithCatalog.method] : {
            summary: 'queryPublishedProcessWithCatalog',
            method: 'post',
            url: (payload) => `/org.gocom.bps.wfclient.process.processMgr.queryPublishedProcessWithCatalog.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.bps.wfclient.process.processMgr.queryPublishedProcessWithCatalog_params','description':'org.gocom.bps.wfclient.process.processMgr.queryPublishedProcessWithCatalog_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.bps.wfclient.process.processMgr.queryPublishedProcessWithCatalog_params'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
