//This file is automatically generated

// recentvisit

import { recentvisit } from '../controller';
export default {
    actions: {
        [recentvisit.add.method] : {
            summary: 'add',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.participantselect.recentvisit.add.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.participantselect.recentvisit.add_params','description':'org.gocom.components.coframe.participantselect.recentvisit.add_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.participantselect.recentvisit.add_params'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
