//This file is automatically generated

// roleselect

import { roleselect } from '../controller';
export default {
    actions: {
        [roleselect.roleList.method] : {
            summary: 'roleList',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.participantselect.roleselect.roleList.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.participantselect.roleselect.roleList_params','description':'org.gocom.components.coframe.participantselect.roleselect.roleList_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.participantselect.roleselect.roleList_params'}}],
        },
        [roleselect.roleListWithPage.method] : {
            summary: 'roleListWithPage',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.participantselect.roleselect.roleListWithPage.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.participantselect.roleselect.roleListWithPage_params','description':'org.gocom.components.coframe.participantselect.roleselect.roleListWithPage_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.participantselect.roleselect.roleListWithPage_params'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
