//This file is automatically generated

// RoleManager

import { RoleManager } from '../controller';
export default {
    actions: {
        [RoleManager.addRole.method] : {
            summary: 'addRole',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.rights.RoleManager.addRole.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.rights.RoleManager.addRole_params','description':'org.gocom.components.coframe.rights.RoleManager.addRole_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.rights.RoleManager.addRole_params'}}],
        },
        [RoleManager.checkRoleExist.method] : {
            summary: 'checkRoleExist',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.rights.RoleManager.checkRoleExist.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.rights.RoleManager.checkRoleExist_params','description':'org.gocom.components.coframe.rights.RoleManager.checkRoleExist_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.rights.RoleManager.checkRoleExist_params'}}],
        },
        [RoleManager.queryAuthorizedRole.method] : {
            summary: 'queryAuthorizedRole',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.rights.RoleManager.queryAuthorizedRole.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.rights.RoleManager.queryAuthorizedRole_params','description':'org.gocom.components.coframe.rights.RoleManager.queryAuthorizedRole_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.rights.RoleManager.queryAuthorizedRole_params'}}],
        },
        [RoleManager.queryRole.method] : {
            summary: 'queryRole',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.rights.RoleManager.queryRole.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.rights.RoleManager.queryRole_params','description':'org.gocom.components.coframe.rights.RoleManager.queryRole_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.rights.RoleManager.queryRole_params'}}],
        },
        [RoleManager.removeRoles.method] : {
            summary: 'removeRoles',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.rights.RoleManager.removeRoles.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.rights.RoleManager.removeRoles_params','description':'org.gocom.components.coframe.rights.RoleManager.removeRoles_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.rights.RoleManager.removeRoles_params'}}],
        },
        [RoleManager.updateRole.method] : {
            summary: 'updateRole',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.rights.RoleManager.updateRole.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.rights.RoleManager.updateRole_params','description':'org.gocom.components.coframe.rights.RoleManager.updateRole_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.rights.RoleManager.updateRole_params'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
