//This file is automatically generated

// rule

import { rule } from '../controller';
export default {
    actions: {
        [rule.delRules.method] : {
            summary: 'delRules',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.entityauth.rule.delRules.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.entityauth.rule.delRules_params','description':'org.gocom.components.coframe.entityauth.rule.delRules_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.entityauth.rule.delRules_params'}}],
        },
        [rule.getConValues.method] : {
            summary: 'getConValues',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.entityauth.rule.getConValues.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.entityauth.rule.getConValues_params','description':'org.gocom.components.coframe.entityauth.rule.getConValues_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.entityauth.rule.getConValues_params'}}],
        },
        [rule.getEntityCapRules.method] : {
            summary: 'getEntityCapRules',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.entityauth.rule.getEntityCapRules.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.entityauth.rule.getEntityCapRules_params','description':'org.gocom.components.coframe.entityauth.rule.getEntityCapRules_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.entityauth.rule.getEntityCapRules_params'}}],
        },
        [rule.getRightValues.method] : {
            summary: 'getRightValues',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.entityauth.rule.getRightValues.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.entityauth.rule.getRightValues_params','description':'org.gocom.components.coframe.entityauth.rule.getRightValues_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.entityauth.rule.getRightValues_params'}}],
        },
        [rule.getRuleCondition.method] : {
            summary: 'getRuleCondition',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.entityauth.rule.getRuleCondition.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.entityauth.rule.getRuleCondition_params','description':'org.gocom.components.coframe.entityauth.rule.getRuleCondition_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.entityauth.rule.getRuleCondition_params'}}],
        },
        [rule.saveRule.method] : {
            summary: 'saveRule',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.entityauth.rule.saveRule.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.entityauth.rule.saveRule_params','description':'org.gocom.components.coframe.entityauth.rule.saveRule_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.entityauth.rule.saveRule_params'}}],
        },
        [rule.storePartyAuth.method] : {
            summary: 'storePartyAuth',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.entityauth.rule.storePartyAuth.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.entityauth.rule.storePartyAuth_params','description':'org.gocom.components.coframe.entityauth.rule.storePartyAuth_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.entityauth.rule.storePartyAuth_params'}}],
        },
        [rule.updateRule.method] : {
            summary: 'updateRule',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.entityauth.rule.updateRule.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.entityauth.rule.updateRule_params','description':'org.gocom.components.coframe.entityauth.rule.updateRule_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.entityauth.rule.updateRule_params'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
