//This file is automatically generated

// service

import { service } from '../controller';
export default {
    actions: {
        [service.getFunctionMenuGraph.method] : {
            summary: 'getFunctionMenuGraph',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.auth.party.graph.service.getFunctionMenuGraph.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.auth.party.graph.service.getFunctionMenuGraph_params','description':'org.gocom.components.coframe.auth.party.graph.service.getFunctionMenuGraph_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.auth.party.graph.service.getFunctionMenuGraph_params'}}],
        },
        [service.getPartyAuthGraph.method] : {
            summary: 'getPartyAuthGraph',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.auth.party.graph.service.getPartyAuthGraph.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.auth.party.graph.service.getPartyAuthGraph_params','description':'org.gocom.components.coframe.auth.party.graph.service.getPartyAuthGraph_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.auth.party.graph.service.getPartyAuthGraph_params'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
