//This file is automatically generated

// TenantManager

import { TenantManager } from '../controller';
export default {
    actions: {
        [TenantManager.addTenant.method] : {
            summary: 'addTenant',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.core.tenant.TenantManager.addTenant.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.core.tenant.TenantManager.addTenant_params','description':'org.gocom.components.coframe.core.tenant.TenantManager.addTenant_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.core.tenant.TenantManager.addTenant_params'}}],
        },
        [TenantManager.deleteTenants.method] : {
            summary: 'deleteTenants',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.core.tenant.TenantManager.deleteTenants.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.core.tenant.TenantManager.deleteTenants_params','description':'org.gocom.components.coframe.core.tenant.TenantManager.deleteTenants_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.core.tenant.TenantManager.deleteTenants_params'}}],
        },
        [TenantManager.queryTenants.method] : {
            summary: 'queryTenants',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.core.tenant.TenantManager.queryTenants.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.core.tenant.TenantManager.queryTenants_params','description':'org.gocom.components.coframe.core.tenant.TenantManager.queryTenants_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.core.tenant.TenantManager.queryTenants_params'}}],
        },
        [TenantManager.updateTenant.method] : {
            summary: 'updateTenant',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.core.tenant.TenantManager.updateTenant.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.core.tenant.TenantManager.updateTenant_params','description':'org.gocom.components.coframe.core.tenant.TenantManager.updateTenant_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.core.tenant.TenantManager.updateTenant_params'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
