//This file is automatically generated

// TenantServiceManager

import { TenantServiceManager } from '../controller';
export default {
    actions: {
        [TenantServiceManager.changeTenant.method] : {
            summary: 'changeTenant',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.auth.TenantServiceManager.changeTenant.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.auth.TenantServiceManager.changeTenant_params','description':'org.gocom.components.coframe.auth.TenantServiceManager.changeTenant_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.auth.TenantServiceManager.changeTenant_params'}}],
        },
        [TenantServiceManager.checkChangeTenant.method] : {
            summary: 'checkChangeTenant',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.auth.TenantServiceManager.checkChangeTenant.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.auth.TenantServiceManager.checkChangeTenant_params','description':'org.gocom.components.coframe.auth.TenantServiceManager.checkChangeTenant_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.auth.TenantServiceManager.checkChangeTenant_params'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
