//This file is automatically generated

// UserManager

import { UserManager } from '../controller';
export default {
    actions: {
        [UserManager.addUser.method] : {
            summary: 'addUser',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.rights.UserManager.addUser.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.rights.UserManager.addUser_params','description':'org.gocom.components.coframe.rights.UserManager.addUser_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.rights.UserManager.addUser_params'}}],
        },
        [UserManager.checkPassword.method] : {
            summary: 'checkPassword',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.rights.UserManager.checkPassword.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.rights.UserManager.checkPassword_params','description':'org.gocom.components.coframe.rights.UserManager.checkPassword_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.rights.UserManager.checkPassword_params'}}],
        },
        [UserManager.checkUser.method] : {
            summary: 'checkUser',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.rights.UserManager.checkUser.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.rights.UserManager.checkUser_params','description':'org.gocom.components.coframe.rights.UserManager.checkUser_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.rights.UserManager.checkUser_params'}}],
        },
        [UserManager.deleteUser.method] : {
            summary: 'deleteUser',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.rights.UserManager.deleteUser.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.rights.UserManager.deleteUser_params','description':'org.gocom.components.coframe.rights.UserManager.deleteUser_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.rights.UserManager.deleteUser_params'}}],
        },
        [UserManager.getCapUser.method] : {
            summary: 'getCapUser',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.rights.UserManager.getCapUser.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.rights.UserManager.getCapUser_params','description':'org.gocom.components.coframe.rights.UserManager.getCapUser_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.rights.UserManager.getCapUser_params'}}],
        },
        [UserManager.getUser.method] : {
            summary: 'getUser',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.rights.UserManager.getUser.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.rights.UserManager.getUser_params','description':'org.gocom.components.coframe.rights.UserManager.getUser_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.rights.UserManager.getUser_params'}}],
        },
        [UserManager.queryDefaultUser.method] : {
            summary: 'queryDefaultUser',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.rights.UserManager.queryDefaultUser.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.rights.UserManager.queryDefaultUser_params','description':'org.gocom.components.coframe.rights.UserManager.queryDefaultUser_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.rights.UserManager.queryDefaultUser_params'}}],
        },
        [UserManager.queryUser.method] : {
            summary: 'queryUser',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.rights.UserManager.queryUser.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.rights.UserManager.queryUser_params','description':'org.gocom.components.coframe.rights.UserManager.queryUser_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.rights.UserManager.queryUser_params'}}],
        },
        [UserManager.updatePasswords.method] : {
            summary: 'updatePasswords',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.rights.UserManager.updatePasswords.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.rights.UserManager.updatePasswords_params','description':'org.gocom.components.coframe.rights.UserManager.updatePasswords_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.rights.UserManager.updatePasswords_params'}}],
        },
        [UserManager.updateUser.method] : {
            summary: 'updateUser',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.rights.UserManager.updateUser.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.rights.UserManager.updateUser_params','description':'org.gocom.components.coframe.rights.UserManager.updateUser_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.rights.UserManager.updateUser_params'}}],
        },
        [UserManager.updateUserPassword.method] : {
            summary: 'updateUserPassword',
            method: 'post',
            url: (payload) => `/org.gocom.components.coframe.rights.UserManager.updateUserPassword.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.coframe.rights.UserManager.updateUserPassword_params','description':'org.gocom.components.coframe.rights.UserManager.updateUserPassword_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.coframe.rights.UserManager.updateUserPassword_params'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
