//This file is automatically generated

// web

import { web } from '../controller';
export default {
    actions: {
        [web.appointActivities4Freeflow.method] : {
            summary: 'appointActivities4Freeflow',
            method: 'post',
            url: (payload) => `/org.gocom.components.bps.wfclient.web.control.webcontrol.appointActivities4Freeflow.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.bps.wfclient.web.control.webcontrol.appointActivities4Freeflow_params','description':'org.gocom.components.bps.wfclient.web.control.webcontrol.appointActivities4Freeflow_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.bps.wfclient.web.control.webcontrol.appointActivities4Freeflow_params'}}],
        },
        [web.appointParticipants4StepActivity.method] : {
            summary: 'appointParticipants4StepActivity',
            method: 'post',
            url: (payload) => `/org.gocom.components.bps.wfclient.web.control.webcontrol.appointParticipants4StepActivity.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.bps.wfclient.web.control.webcontrol.appointParticipants4StepActivity_params','description':'org.gocom.components.bps.wfclient.web.control.webcontrol.appointParticipants4StepActivity_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.bps.wfclient.web.control.webcontrol.appointParticipants4StepActivity_params'}}],
        },
        [web.fetchMessageList.method] : {
            summary: 'fetchMessageList',
            method: 'post',
            url: (payload) => `/org.gocom.components.bps.wfclient.web.control.webcontrol.fetchMessageList.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.bps.wfclient.web.control.webcontrol.fetchMessageList_params','description':'org.gocom.components.bps.wfclient.web.control.webcontrol.fetchMessageList_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.bps.wfclient.web.control.webcontrol.fetchMessageList_params'}}],
        },
        [web.getActivitesNeedAppointParticipant.method] : {
            summary: 'getActivitesNeedAppointParticipant',
            method: 'post',
            url: (payload) => `/org.gocom.components.bps.wfclient.web.control.webcontrol.getActivitesNeedAppointParticipant.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.bps.wfclient.web.control.webcontrol.getActivitesNeedAppointParticipant_params','description':'org.gocom.components.bps.wfclient.web.control.webcontrol.getActivitesNeedAppointParticipant_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.bps.wfclient.web.control.webcontrol.getActivitesNeedAppointParticipant_params'}}],
        },
        [web.getAppointActivityType.method] : {
            summary: 'getAppointActivityType',
            method: 'post',
            url: (payload) => `/org.gocom.components.bps.wfclient.web.control.webcontrol.getAppointActivityType.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.bps.wfclient.web.control.webcontrol.getAppointActivityType_params','description':'org.gocom.components.bps.wfclient.web.control.webcontrol.getAppointActivityType_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.bps.wfclient.web.control.webcontrol.getAppointActivityType_params'}}],
        },
        [web.getProcessGraph.method] : {
            summary: 'getProcessGraph',
            method: 'post',
            url: (payload) => `/org.gocom.components.bps.wfclient.web.control.webcontrol.getProcessGraph.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.bps.wfclient.web.control.webcontrol.getProcessGraph_params','description':'org.gocom.components.bps.wfclient.web.control.webcontrol.getProcessGraph_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.bps.wfclient.web.control.webcontrol.getProcessGraph_params'}}],
        },
        [web.getWorkItemForm.method] : {
            summary: 'getWorkItemForm',
            method: 'post',
            url: (payload) => `/org.gocom.components.bps.wfclient.web.control.webcontrol.getWorkItemForm.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.bps.wfclient.web.control.webcontrol.getWorkItemForm_params','description':'org.gocom.components.bps.wfclient.web.control.webcontrol.getWorkItemForm_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.bps.wfclient.web.control.webcontrol.getWorkItemForm_params'}}],
        },
        [web.getWorkItemsByProcInstId.method] : {
            summary: 'getWorkItemsByProcInstId',
            method: 'post',
            url: (payload) => `/org.gocom.components.bps.wfclient.web.control.webcontrol.getWorkItemsByProcInstId.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.bps.wfclient.web.control.webcontrol.getWorkItemsByProcInstId_params','description':'org.gocom.components.bps.wfclient.web.control.webcontrol.getWorkItemsByProcInstId_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.bps.wfclient.web.control.webcontrol.getWorkItemsByProcInstId_params'}}],
        },
        [web.isActivitiesAppointed.method] : {
            summary: 'isActivitiesAppointed',
            method: 'post',
            url: (payload) => `/org.gocom.components.bps.wfclient.web.control.webcontrol.isActivitiesAppointed.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.bps.wfclient.web.control.webcontrol.isActivitiesAppointed_params','description':'org.gocom.components.bps.wfclient.web.control.webcontrol.isActivitiesAppointed_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.bps.wfclient.web.control.webcontrol.isActivitiesAppointed_params'}}],
        },
        [web.loadFiles.method] : {
            summary: 'loadFiles',
            method: 'post',
            url: (payload) => `/com.primeton.components.web.fileupload.fileupload.loadFiles.biz.ext`,
            parameters: [{'in':'body','name':'com.primeton.components.web.fileupload.fileupload.loadFiles_params','description':'com.primeton.components.web.fileupload.fileupload.loadFiles_params','required':true,'schema':{'$ref':'#/definitions/com.primeton.components.web.fileupload.fileupload.loadFiles_params'}}],
        },
        [web.queryAnnotateListByProcessInstID.method] : {
            summary: 'queryAnnotateListByProcessInstID',
            method: 'post',
            url: (payload) => `/org.gocom.components.bps.wfclient.web.control.webcontrol.queryAnnotateListByProcessInstID.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.bps.wfclient.web.control.webcontrol.queryAnnotateListByProcessInstID_params','description':'org.gocom.components.bps.wfclient.web.control.webcontrol.queryAnnotateListByProcessInstID_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.bps.wfclient.web.control.webcontrol.queryAnnotateListByProcessInstID_params'}}],
        },
        [web.queryAnnotateListByTaskID.method] : {
            summary: 'queryAnnotateListByTaskID',
            method: 'post',
            url: (payload) => `/org.gocom.components.bps.wfclient.web.control.webcontrol.queryAnnotateListByTaskID.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.bps.wfclient.web.control.webcontrol.queryAnnotateListByTaskID_params','description':'org.gocom.components.bps.wfclient.web.control.webcontrol.queryAnnotateListByTaskID_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.bps.wfclient.web.control.webcontrol.queryAnnotateListByTaskID_params'}}],
        },
        [web.queryParticipants.method] : {
            summary: 'queryParticipants',
            method: 'post',
            url: (payload) => `/org.gocom.components.bps.wfclient.web.control.webcontrol.queryParticipants.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.bps.wfclient.web.control.webcontrol.queryParticipants_params','description':'org.gocom.components.bps.wfclient.web.control.webcontrol.queryParticipants_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.bps.wfclient.web.control.webcontrol.queryParticipants_params'}}],
        },
        [web.queryPressListByProcessInstID.method] : {
            summary: 'queryPressListByProcessInstID',
            method: 'post',
            url: (payload) => `/org.gocom.components.bps.wfclient.web.control.webcontrol.queryPressListByProcessInstID.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.bps.wfclient.web.control.webcontrol.queryPressListByProcessInstID_params','description':'org.gocom.components.bps.wfclient.web.control.webcontrol.queryPressListByProcessInstID_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.bps.wfclient.web.control.webcontrol.queryPressListByProcessInstID_params'}}],
        },
        [web.queryPressListByTaskID.method] : {
            summary: 'queryPressListByTaskID',
            method: 'post',
            url: (payload) => `/org.gocom.components.bps.wfclient.web.control.webcontrol.queryPressListByTaskID.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.bps.wfclient.web.control.webcontrol.queryPressListByTaskID_params','description':'org.gocom.components.bps.wfclient.web.control.webcontrol.queryPressListByTaskID_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.bps.wfclient.web.control.webcontrol.queryPressListByTaskID_params'}}],
        },
        [web.queryProcessAndActivity.method] : {
            summary: 'queryProcessAndActivity',
            method: 'post',
            url: (payload) => `/org.gocom.components.bps.wfclient.web.control.webcontrol.queryProcessAndActivity.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.bps.wfclient.web.control.webcontrol.queryProcessAndActivity_params','description':'org.gocom.components.bps.wfclient.web.control.webcontrol.queryProcessAndActivity_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.bps.wfclient.web.control.webcontrol.queryProcessAndActivity_params'}}],
        },
        [web.queryStepActivities.method] : {
            summary: 'queryStepActivities',
            method: 'post',
            url: (payload) => `/org.gocom.components.bps.wfclient.web.control.webcontrol.queryStepActivities.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.bps.wfclient.web.control.webcontrol.queryStepActivities_params','description':'org.gocom.components.bps.wfclient.web.control.webcontrol.queryStepActivities_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.bps.wfclient.web.control.webcontrol.queryStepActivities_params'}}],
        },
        [web.searchParticipants.method] : {
            summary: 'searchParticipants',
            method: 'post',
            url: (payload) => `/org.gocom.components.bps.wfclient.web.control.webcontrol.searchParticipants.biz.ext`,
            parameters: [{'in':'body','name':'org.gocom.components.bps.wfclient.web.control.webcontrol.searchParticipants_params','description':'org.gocom.components.bps.wfclient.web.control.webcontrol.searchParticipants_params','required':true,'schema':{'$ref':'#/definitions/org.gocom.components.bps.wfclient.web.control.webcontrol.searchParticipants_params'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
