

export default {
    noticeLists:{
        all:[
            {
                title:'关于信息技术中心研发出新的功能，办公效率提升200',
                who:'行政服务平台',
                content:'最近的行政服务平台用户：根据公司物业管理安排,请同事们吧工位摆放整齐,最近的行政服务平台用户：根据公司物业管理安排,请同事们吧工位摆放整齐',
                time:'2020-12-25',
            },
            {
                title:'关于信息技术中心研发出新的功能，办公效率提升200',
                who:'行政服务平台',
                content:'最近的行政服务平台用户：根据公司物业管理安排,请同事们吧工位摆放整齐,最近的行政服务平台用户：根据公司物业管理安排,请同事们吧工位摆放整齐',
                time:'2020-12-25',
            },
            {
                title:'关于信息技术中心研发出新的功能，办公效率提升200',
                who:'行政服务平台',
                content:'最近的行政服务平台用户：根据公司物业管理安排,请同事们吧工位摆放整齐,最近的行政服务平台用户：根据公司物业管理安排,请同事们吧工位摆放整齐',
                time:'2020-12-25',
            },
            {
                title:'关于信息技术中心研发出新的功能，办公效率提升200',
                who:'行政服务平台',
                content:'最近的行政服务平台用户：根据公司物业管理安排,请同事们吧工位摆放整齐,最近的行政服务平台用户：根据公司物业管理安排,请同事们吧工位摆放整齐',
                time:'2020-12-25',
            },
            {
                title:'关于信息技术中心研发出新的功能，办公效率提升200',
                who:'行政服务平台',
                content:'最近的行政服务平台用户：根据公司物业管理安排,请同事们吧工位摆放整齐,最近的行政服务平台用户：根据公司物业管理安排,请同事们吧工位摆放整齐',
                time:'2020-12-25',
            },
        ],
        system:[
            {
                title:'关于信息技术中心研发出新的功能，办公效率提升200',
                who:'行政服务平台',
                content:'最近的行政服务平台用户：根据公司物业管理安排,请同事们吧工位摆放整齐,最近的行政服务平台用户：根据公司物业管理安排,请同事们吧工位摆放整齐',
                time:'2020-12-25',
            },

        ],
        restaurant:[
            {
                title:'关于信息技术中心研发出新的功能，办公效率提升200',
                who:'行政服务平台',
                content:'最近的行政服务平台用户：根据公司物业管理安排,请同事们吧工位摆放整齐,最近的行政服务平台用户：根据公司物业管理安排,请同事们吧工位摆放整齐',
                time:'2020-12-25',
            },
            {
                title:'关于信息技术中心研发出新的功能，办公效率提升200',
                who:'行政服务平台',
                content:'最近的行政服务平台用户：根据公司物业管理安排,请同事们吧工位摆放整齐,最近的行政服务平台用户：根据公司物业管理安排,请同事们吧工位摆放整齐',
                time:'2020-12-25',
            },
            {
                title:'关于信息技术中心研发出新的功能，办公效率提升200',
                who:'行政服务平台',
                content:'最近的行政服务平台用户：根据公司物业管理安排,请同事们吧工位摆放整齐,最近的行政服务平台用户：根据公司物业管理安排,请同事们吧工位摆放整齐',
                time:'2020-12-25',
            },

        ],
        property:[
            {
                title:'关于信息技术中心研发出新的功能，办公效率提升200',
                who:'行政服务平台',
                content:'最近的行政服务平台用户：根据公司物业管理安排,请同事们吧工位摆放整齐,最近的行政服务平台用户：根据公司物业管理安排,请同事们吧工位摆放整齐',
                time:'2020-12-25',
            },
            {
                title:'关于信息技术中心研发出新的功能，办公效率提升200',
                who:'行政服务平台',
                content:'最近的行政服务平台用户：根据公司物业管理安排,请同事们吧工位摆放整齐,最近的行政服务平台用户：根据公司物业管理安排,请同事们吧工位摆放整齐',
                time:'2020-12-25',
            },
            {
                title:'关于信息技术中心研发出新的功能，办公效率提升200',
                who:'行政服务平台',
                content:'最近的行政服务平台用户：根据公司物业管理安排,请同事们吧工位摆放整齐,最近的行政服务平台用户：根据公司物业管理安排,请同事们吧工位摆放整齐',
                time:'2020-12-25',
            },
            {
                title:'关于信息技术中心研发出新的功能，办公效率提升200',
                who:'行政服务平台',
                content:'最近的行政服务平台用户：根据公司物业管理安排,请同事们吧工位摆放整齐,最近的行政服务平台用户：根据公司物业管理安排,请同事们吧工位摆放整齐',
                time:'2020-12-25',
            },
            {
                title:'关于信息技术中心研发出新的功能，办公效率提升200',
                who:'行政服务平台',
                content:'最近的行政服务平台用户：根据公司物业管理安排,请同事们吧工位摆放整齐,最近的行政服务平台用户：根据公司物业管理安排,请同事们吧工位摆放整齐',
                time:'2020-12-25',
            },
        ]
    },
    news:{
        all:[
            {
                src:'https://axure-file.lanhuapp.com/1bd99c9f-823c-4505-a248-0fe8d210da20__5e9d0febbb4b6d4c69ea2a2bbb6f911f.svg',
                title:'信息技术中心研发出新的功能，办公效率提升200%',
                from :'百度新闻',
                time:'2020-02-15'
            }
        ],
        hot:[
            {
                src:'https://axure-file.lanhuapp.com/1bd99c9f-823c-4505-a248-0fe8d210da20__5e9d0febbb4b6d4c69ea2a2bbb6f911f.svg',
                title:'信息技术中心研发出新的功能，办公效率提升200%',
                from :'百度新闻',
                time:'2020-02-15'
            },
            {
                src:'https://axure-file.lanhuapp.com/1bd99c9f-823c-4505-a248-0fe8d210da20__5e9d0febbb4b6d4c69ea2a2bbb6f911f.svg',
                title:'信息技术中心研发出新的功能，办公效率提升200%',
                from :'百度新闻',
                time:'2020-02-15'
            }
        ],
        events:[
            {
                src:'https://axure-file.lanhuapp.com/1bd99c9f-823c-4505-a248-0fe8d210da20__5e9d0febbb4b6d4c69ea2a2bbb6f911f.svg',
                title:'信息技术中心研发出新的功能，办公效率提升200%',
                from :'百度新闻',
                time:'2020-02-15'
            },
            {
                src:'https://axure-file.lanhuapp.com/1bd99c9f-823c-4505-a248-0fe8d210da20__5e9d0febbb4b6d4c69ea2a2bbb6f911f.svg',
                title:'信息技术中心研发出新的功能，办公效率提升200%',
                from :'百度新闻',
                time:'2020-02-15'
            },
            {
                src:'https://axure-file.lanhuapp.com/1bd99c9f-823c-4505-a248-0fe8d210da20__5e9d0febbb4b6d4c69ea2a2bbb6f911f.svg',
                title:'信息技术中心研发出新的功能，办公效率提升200%',
                from :'百度新闻',
                time:'2020-02-15'
            },
            {
                src:'https://axure-file.lanhuapp.com/1bd99c9f-823c-4505-a248-0fe8d210da20__5e9d0febbb4b6d4c69ea2a2bbb6f911f.svg',
                title:'信息技术中心研发出新的功能，办公效率提升200%',
                from :'百度新闻',
                time:'2020-02-15'
            }
        ]
    },
    topics:[
        {
            topicTitle:'哪个饭堂的饭香',
        },
        {
            topicTitle:'哪个饭堂的饭香',
        },
        {
            topicTitle:'哪个饭堂的饭香',
        },
        {
            topicTitle:'哪个饭堂的饭香',
        },
        {
            topicTitle:'哪个饭堂的饭香',
        },

    ],
    comments:[
        {
            avatar:'https://axure-file.lanhuapp.com/1bd99c9f-823c-4505-a248-0fe8d210da20__a63db0a228d80c34501a34fa50d27746.svg',
            username:'username',
            belongToTopic:'哪个饭堂的饭香',
            content:'dsadsadnaskdasdasd',
            tag:'hot'
        },
        {
            avatar:'https://axure-file.lanhuapp.com/1bd99c9f-823c-4505-a248-0fe8d210da20__a63db0a228d80c34501a34fa50d27746.svg',
            username:'username',
            belongToTopic:'哪个饭堂的饭香',
            content:'dsadsadnaskdasdasd',
            tag:'like'
        },
        {
            avatar:'https://axure-file.lanhuapp.com/1bd99c9f-823c-4505-a248-0fe8d210da20__a63db0a228d80c34501a34fa50d27746.svg',
            username:'username',
            belongToTopic:'哪个饭堂的饭香',
            content:'dsadsadnaskdasdasd',
            tag:'like'
        },
        {
            avatar:'https://axure-file.lanhuapp.com/1bd99c9f-823c-4505-a248-0fe8d210da20__a63db0a228d80c34501a34fa50d27746.svg',
            username:'username',
            belongToTopic:'哪个饭堂的饭香',
            content:'dsadsadnaskdasdasd',
            tag:'like'
        }
    ]
}