//This file is automatically generated

// 人员健康管理

import { HealthApiController } from '../controller';
export default {
    actions: {
        [HealthApiController.getHealthInfo.method] : {
            summary: '获取人员健康信息',
            method: 'get',
            url: (payload) => `/api/platform/health/getHealthInfo`,
            parameters: [],
        },
        [HealthApiController.updateHealthInfo.method] : {
            summary: '根据人员id更新人员健康录入信息',
            method: 'post',
            url: (payload) => `/api/platform/health/updateHealthInfo`,
            parameters: [{'in':'body','name':'healthEntity','description':'healthEntity','required':true,'schema':{'$ref':'#/definitions/健康打卡项'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
