//This file is automatically generated

// 帮助中心

import { HelpControllerImpl } from '../controller';
export default {
    actions: {
        [HelpControllerImpl.AddCommonProblem.method] : {
            summary: '新增一个常见问题',
            method: 'post',
            url: (payload) => `/api/platform/help/addCommonProblem`,
            parameters: [{'in':'body','name':'entity','description':'entity','required':true,'schema':{'$ref':'#/definitions/常用问题'}}],
        },
        [HelpControllerImpl.AddDemandFeedbackReply.method] : {
            summary: '新增一个需求反馈回复',
            method: 'post',
            url: (payload) => `/api/platform/help/addDemandFeedbackReply`,
            parameters: [{'in':'body','name':'vo','description':'vo','required':true,'schema':{'$ref':'#/definitions/DemandFeedbackReplyVO'}}],
        },
        [HelpControllerImpl.AddProductIntroduction.method] : {
            summary: '新增一个产品介绍',
            method: 'post',
            url: (payload) => `/api/platform/help/addProductIntroduction`,
            parameters: [{'in':'body','name':'entity','description':'entity','required':true,'schema':{'$ref':'#/definitions/产品介绍'}}],
        },
        [HelpControllerImpl.DelCommonProblem.method] : {
            summary: '删除一个常见问题',
            method: 'delete',
            url: (payload) => `/api/platform/help/deleteCommonProblem/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'主键','required':true,'type':'integer','format':'int32'}],
        },
        [HelpControllerImpl.DelProductIntroduction.method] : {
            summary: '删除一个产品介绍',
            method: 'delete',
            url: (payload) => `/api/platform/help/delProductIntroduction/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'主键','required':true,'type':'integer','format':'int32'}],
        },
        [HelpControllerImpl.UpdateCommonProblem.method] : {
            summary: '修改一个常见问题',
            method: 'put',
            url: (payload) => `/api/platform/help/updateCommonProblem`,
            parameters: [{'in':'body','name':'entity','description':'entity','required':true,'schema':{'$ref':'#/definitions/常用问题'}}],
        },
        [HelpControllerImpl.UpdateProductIntroduction.method] : {
            summary: '修改一个产品介绍',
            method: 'put',
            url: (payload) => `/api/platform/help/updateProductIntroduction`,
            parameters: [{'in':'body','name':'entity','description':'entity','required':true,'schema':{'$ref':'#/definitions/常用问题'}}],
        },
        [HelpControllerImpl.addDemandFeedback.method] : {
            summary: '新增一个需求反馈',
            method: 'post',
            url: (payload) => `/api/platform/help/addDemandFeedback`,
            parameters: [{'in':'body','name':'vo','description':'vo','required':true,'schema':{'$ref':'#/definitions/DemandFeedbackVO'}}],
        },
        [HelpControllerImpl.queryByIdJoinReply.method] : {
            summary: '根据ID查询一个需求反馈',
            method: 'get',
            url: (payload) => `/api/platform/help/demandFeedback/queryByIdJoinReply/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'主键','required':true,'type':'integer','format':'int32'}],
        },
        [HelpControllerImpl.queryByTitle.method] : {
            summary: '根据标题模糊查询所有常见问题',
            method: 'get',
            url: (payload) => `/api/platform/help/commonProblem/queryByTitle`,
            parameters: [{'name':'title','in':'query','description':'标题','required':false,'type':'string','allowEmptyValue':false}],
        },
        [HelpControllerImpl.queryDemandFeedback.method] : {
            summary: '查询所有需求反馈',
            method: 'get',
            url: (payload) => `/api/platform/help/queryDemandFeedback`,
            parameters: [],
        },
        [HelpControllerImpl.queryProductIntroduction.method] : {
            summary: '查询所有产品介绍',
            method: 'get',
            url: (payload) => `/api/platform/help/queryProductIntroduction`,
            parameters: [],
        },
        [HelpControllerImpl.updateDemandFeedbackType.method] : {
            summary: '更改需求反馈的状态',
            method: 'put',
            url: (payload) => `/api/platform/help/updateDemandFeedbackType/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'主键','required':true,'type':'integer','format':'int32'}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
