export default [
    {
        path:'/Question',
        name:'Question',
        redirect:'/',
        meta:{
            name:'常见问题'
        },
        component:()=>import('@/views/Home.vue')
    },
    {
        path:'/ProductsInc',
        name:'ProductsInc',
        meta:{
            name:'产品介绍',
            tag:'ProductsInc'
        },
        component:()=>import('@/views/Product/ProductsInc.vue')
    },
    {
        path:'/ProductInc/:id',
        name:'ProductInc',
        meta:{
            name:'产品介绍',
            leave:'LeaveTwoRouter',
            tag:'ProductInc'
        },
        component:()=>import('@/views/Product/ProductInc.vue')
    },
    {
        path:'/DemanFeedback',
        name:'DemanFeedback',
        meta:{
            name:'需求反馈'
        },
        component:()=>import('@/views/DemanFeedback.vue')
    },
    {
        path:'/Replay',
        name:'Replay',
        meta:{
            name:'回复',
            leave:'LeaveTwoRouter',
        },
        component:()=>import('@/views/Replay/Replay.vue')
    },
    {
        path:'/ReplayDetail',
        name:'ReplayDetail',
        meta:{
            name:'ReplayDetail',
            leave:'LeaveTwoRouter',
        },
        component:()=>import('@/views/Replay/ReplayDetail.vue')
    },
]