

export default [
    {
        path:'/Cultural',
        name:'文化建设',
        redirect:'/Cultural/Notice/',
        meta:{
            name:'文化建设',
            tag:'文化建设',
            showNav:false
        },
        component:()=>import('@/views/Cultural/index'),
        children:[
            {
                path:'Notice',
                name:'公告列表',
                meta:{
                    name:'公告列表',
                    tag:'公告列表',
                    showNav:false
                },
                component:()=>import('@/views/Cultural/Notice/index'),
            },
            {
                path:'News',
                name:'企业新闻',
                meta:{
                    name:'企业新闻',
                    tag:'企业新闻',
                    showNav:false
                },
                component:()=>import('@/views/Cultural/News/index'),
            },
            {
                path:'Communication',
                name:'交流圈',
                meta:{
                    name:'交流圈',
                    tag:'交流圈',
                    showNav:false
                },
                component:()=>import('@/views/Cultural/Communication/index'),

            }
        ]
    },
    {
        path:'/Cultural/:id',
        name:'公告详情',
        meta:{
            showNav:true,
            name:'公告详情',
            leave:3,

        },
        component:()=>import('@/views/Cultural/Notice/Detail'),
    },
    {
        path:'/Cultural/New/:id',
        name:'企业新闻详情',
        meta:{
            showNav:true,
            name:'企业新闻',
            leave:3,

        },
        component:()=>import('@/views/Cultural/News/Detail'),
    },
    {
        path:'/Comments/:id',
        name:'交流圈-评论详情',
        meta:{
            name:'交流圈-评论详情',
            tag:'交流圈-评论详情',
            showNav:true,
            leave:3,

        },
        component:()=>import('@/views/Cultural/Communication/Comments'),
    },
    {
        path:'/Communication/send',
        name:'发帖子',
        meta:{
            name:'发帖子',
            tag:'发帖子',
            showNav:true,
            leave:3,

        },
        component:()=>import('@/views/Cultural/Communication/send'),
    },
    {
        path:'/Communication/TopicList',
        name:'话题列表',
        meta:{
            name:'话题列表',
            tag:'话题列表',
            showNav:true,
            leave: 3
        },
        component:()=>import('@/views/Cultural/Communication/TopicList')
    }
]