export default [
    {
        path:'/Guest',
        meta:{
            name:'访客预约',
            tag:'Guest',
            leave:'LeaveTwoRouter'
        },
        component:()=>import('@/views/Guest/index'),
        children:[
            {
                path:'/',
                name:'Guest',
                meta:{
                    name:'访客预约',
                    tag:'Guest',
                    leave:'LeaveTwoRouter'
                },
                component:()=>import('@/views/Guest/Guest'),
            },
            {
                path:'Approve',
                name:'Approve',
                meta:{
                    name:'我的审批',
                    tag:'Approve',
                    leave:'LeaveTwoRouter'
                },
                component:()=>import('@/views/Guest/Approve')
            },
            {
                path:'Reserve',
                name:'Reserve',
                meta:{
                    name:'我的预约',
                    tag:'Reserve',
                    leave:'LeaveTwoRouter'
                },
                component:()=>import('@/views/Guest/Reserve')
            }
        ]
    },
    {
        path:'/Guest/:id',
        name:'GuestDetail',
        meta:{
            name:'访客详情',
            tag:'GuestDetail',
            leave:'LeaveTwoRouter'
        },
        component:()=>import('@/views/Guest/GuestDetil')
    },
    {
        path:'/Reserve/:id',
        name:'ReserveDetail',
        meta:{
            name:'访客详情',
            tag:'ReserveDetail',
            leave:'LeaveTwoRouter'
        },
        component:()=>import('@/views/Guest/ReserveDetail')
    }
]