export default [
    {
        path:'/Guest',
        redirect:'Guest/',
        name:'访客预约',
        meta:{
            name:'访客预约',
            tag:'Guest',
            leave:'LeaveTwoRouter'
        },
        component:()=>import('@/views/Guest/index'),
        children:[
            {
                path:'/',
                name:'Guest',
                meta:{
                    name:'访客预约',
                    tag:'Guest',
                    leave:2,
                    showNav:true,
                    showTabbar:true
                },
                component:()=>import('@/views/Guest/Guest'),
            },
            {
                path:'Approve',
                name:'Approve',
                meta:{
                    name:'我的审批',
                    tag:'Approve',
                    leave:2,
                    showNav: true,
                    showTabbar:true
                },
                component:()=>import('@/views/Guest/Approve')
            },
            {
                path:'Reserve',
                name:'Reserve',
                meta:{
                    name:'我的预约',
                    tag:'Reserve',
                    leave:2,
                    showNav: true,
                    showTabbar:true
                },
                component:()=>import('@/views/Guest/Reserve')
            }
        ]
    },
    {
        path:'/Guest/:id',
        name:'GuestDetail',
        meta:{
            name:'访客详情',
            tag:'GuestDetail',
            leave:3,
            showNav:true,
            showTabbar:true,
            backRouter:'Reserve',
        },
        component:()=>import('@/views/Guest/GuestDetil')
    },
    {
        path:'/Reserve/:id',
        name:'ReserveDetail',
        meta:{
            name:'审批详情',
            tag:'ReserveDetail',
            leave:3,
            showNav:true,
            showTabbar:true,
            backRouter:'Approve',
        },
        component:()=>import('@/views/Guest/ReserveDetail')
    },
    {
        path:'/RejectConfirm',
        name:'RejectConfirm',
        meta:{
            name:'确认拒绝',
            tag:'RejectConfirm',
            leave:3,
            showNav:true,
            backRouter:'Reserve',
        },
        component:()=>import('@/views/Guest/RejectConfirm')
    }
]