
export default [
    {
        path:'/HelpCenter',
        component:()=>import('@/views/HelpCenter/index'),
        children:[
            {
                path:'/',
                name:'常见问题',
                meta:{
                    name:'常见问题',
                    tag:'Question',
                    showTabbar:true,
                    leave:'LeaveTwoRouter'
                },
                component:()=>import('@/views/HelpCenter/Question')
            },
            {
                path:'ProductsInc',
                name:'产品介绍',
                meta:{
                    name:'产品介绍',
                    tag:'ProductsInc',
                    showTabbar:true,
                    leave:'LeaveTwoRouter'

                },
                component:()=>import('@/views/HelpCenter/Product/ProductsInc.vue')
            },
            {
                path:'ProductInc/:id',
                name:'ProductInc',
                meta:{
                    name:'产品介绍',
                    leave:'LeaveTwoRouter',
                    tag:'ProductInc'
                },
                component:()=>import('@/views/HelpCenter/Product/ProductInc.vue')
            },
            {
                path:'DemanFeedback',
                name:'需求反馈',
                meta:{
                    name:'需求反馈',
                    showTabbar:true,
                    leave:'LeaveTwoRouter'

                },
                component:()=>import('@/views/HelpCenter/DemanFeedback.vue')
            },
            {
                path:'Replay',
                name:'Replay',
                meta:{
                    name:'回复',
                    leave:'LeaveTwoRouter',
                },
                component:()=>import('@/views/HelpCenter/Replay/Replay.vue')
            },
            {
                path:'ReplayDetail',
                name:'ReplayDetail',
                meta:{
                    name:'ReplayDetail',
                    leave:'LeaveTwoRouter',
                },
                component:()=>import('@/views/HelpCenter/Replay/ReplayDetail.vue')
            },
        ]
    }
]