//This file is automatically generated

// 预约中心

import { BarberControllerImpl } from '../controller';
export default {
    actions: {
        [BarberControllerImpl.addBarber.method] : {
            summary: '发布理发室',
            method: 'post',
            url: (payload) => `/api/platform/order/barber/addBarber`,
            parameters: [{'in':'body','name':'nNarberVO','description':'nNarberVO','required':true,'schema':{'$ref':'#/definitions/NBarberVo'}}],
        },
        [BarberControllerImpl.addBarberUser.method] : {
            summary: '预约理发室',
            method: 'post',
            url: (payload) => `/api/platform/order/barber/addBarberUser/${payload.barberId}`,
            parameters: [{'name':'barberId','in':'path','description':'理发室id','required':true,'type':'integer','format':'int32'}],
        },
        [BarberControllerImpl.addClinic.method] : {
            summary: '发布医务室',
            method: 'post',
            url: (payload) => `/api/platform/order/clinic/addClinic`,
            parameters: [{'in':'body','name':'nNarberVO','description':'nNarberVO','required':true,'schema':{'$ref':'#/definitions/NClinicVo'}}],
        },
        [BarberControllerImpl.addClinicUser.method] : {
            summary: '预约医务室',
            method: 'post',
            url: (payload) => `/api/platform/order/clinic/addClinicUser/${payload.clinicId}`,
            parameters: [{'name':'clinicId','in':'path','description':'医务室id','required':true,'type':'integer','format':'int32'}],
        },
        [BarberControllerImpl.deleteBarber.method] : {
            summary: '删除一个发布的理发室信息',
            method: 'delete',
            url: (payload) => `/api/platform/order/barber/deleteBarber/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'主键','required':true,'type':'integer','format':'int32'}],
        },
        [BarberControllerImpl.deleteClinic.method] : {
            summary: '删除一个发布的医务室信息',
            method: 'delete',
            url: (payload) => `/api/platform/order/clinic/deleteClinic/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'主键','required':true,'type':'integer','format':'int32'}],
        },
        [BarberControllerImpl.queryAllForBarber.method] : {
            summary: '管理员查询全部预约情况',
            method: 'get',
            url: (payload) => `/api/platform/order/barber/queryAllByAdmin`,
            parameters: [],
        },
        [BarberControllerImpl.queryAllForClinic.method] : {
            summary: '管理员查询全部预约情况',
            method: 'get',
            url: (payload) => `/api/platform/order/clinic/queryAllByAdmin`,
            parameters: [],
        },
        [BarberControllerImpl.queryByMonthForBarber.method] : {
            summary: '根据日期进行查询预约情况',
            method: 'get',
            url: (payload) => `/api/platform/order/barber/queryByMonth/${payload.month}`,
            parameters: [{'name':'month','in':'path','description':'日期','required':true,'type':'string'}],
        },
        [BarberControllerImpl.queryByMonthForClinic.method] : {
            summary: '根据日期进行查询预约情况',
            method: 'get',
            url: (payload) => `/api/platform/order/clinic/queryByMonth/${payload.month}`,
            parameters: [{'name':'month','in':'path','description':'日期','required':true,'type':'string'}],
        },
        [BarberControllerImpl.queryByStateForBarber.method] : {
            summary: '根据预约状态查询理发室的预约情况',
            method: 'get',
            url: (payload) => `/api/platform/order/barber/queryByState/${payload.state}`,
            parameters: [{'name':'state','in':'path','description':'状态','required':true,'type':'string'}],
        },
        [BarberControllerImpl.queryByStateForClinic.method] : {
            summary: '根据预约状态查询医务室的预约情况',
            method: 'get',
            url: (payload) => `/api/platform/order/clinic/queryByState/${payload.state}`,
            parameters: [{'name':'state','in':'path','description':'状态','required':true,'type':'string'}],
        },
        [BarberControllerImpl.queryByTypeAndDateForBarber.method] : {
            summary: '根据预约类型和日期查询理发室的预约情况  名额',
            method: 'get',
            url: (payload) => `/api/platform/order/barber/queryByDate/${payload.type}/${payload.date}`,
            parameters: [{'name':'date','in':'path','description':'日期','required':true,'type':'string'},{'name':'type','in':'path','description':'类型','required':true,'type':'string'}],
        },
        [BarberControllerImpl.queryByTypeAndDateForClinic.method] : {
            summary: '根据预约类型和日期查询医务室的预约情况  名额',
            method: 'get',
            url: (payload) => `/api/platform/order/clinic/queryByDate/${payload.type}/${payload.date}`,
            parameters: [{'name':'date','in':'path','description':'日期','required':true,'type':'string'},{'name':'type','in':'path','description':'类型','required':true,'type':'string'}],
        },
        [BarberControllerImpl.updateBarber.method] : {
            summary: '修改发布的理发室信息',
            method: 'put',
            url: (payload) => `/api/platform/order/barber/updateBarber`,
            parameters: [{'in':'body','name':'upBarberVo','description':'upBarberVo','required':true,'schema':{'$ref':'#/definitions/UpBarberVo'}}],
        },
        [BarberControllerImpl.updateCancelForBarber.method] : {
            summary: '取消理发室预约',
            method: 'put',
            url: (payload) => `/api/platform/order/barber/updateBarberUserForCancel/${payload.barberId}`,
            parameters: [{'name':'barberId','in':'path','description':'理发室id','required':true,'type':'integer','format':'int32'}],
        },
        [BarberControllerImpl.updateCancelForClinic.method] : {
            summary: '取消医务室预约',
            method: 'put',
            url: (payload) => `/api/platform/order/clinic/updateClinicUserForCancel/${payload.clinicId}`,
            parameters: [{'name':'clinicId','in':'path','description':'医务室id','required':true,'type':'integer','format':'int32'}],
        },
        [BarberControllerImpl.updateClinic.method] : {
            summary: '修改发布的医务室信息',
            method: 'put',
            url: (payload) => `/api/platform/order/clinic/updateClinic`,
            parameters: [{'in':'body','name':'upClinicVo','description':'upClinicVo','required':true,'schema':{'$ref':'#/definitions/UpClinicVo'}}],
        },
        [BarberControllerImpl.updateSignForBarber.method] : {
            summary: '理发室预约签到',
            method: 'put',
            url: (payload) => `/api/platform/order/barber/updateBarberUserForSign/${payload.barberId}`,
            parameters: [{'name':'barberId','in':'path','description':'理发室id','required':true,'type':'integer','format':'int32'}],
        },
        [BarberControllerImpl.updateSignForClinic.method] : {
            summary: '医务室预约签到',
            method: 'put',
            url: (payload) => `/api/platform/order/clinic/updateClinicUserForSign/${payload.clinicId}`,
            parameters: [{'name':'clinicId','in':'path','description':'医务室id','required':true,'type':'integer','format':'int32'}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
