export default {
    listData:[
        {
            id:1,
            title:'one'
        },
        {
            id:2,
            title:'two'
        }
    ],
    feedback:[
        {
            id:1,
            user:{
                avatar:'https://axure-file.lanhuapp.com/1bd99c9f-823c-4505-a248-0fe8d210da20__ce77de2733d2f72b27f5abf616a7b5ac.svg',
                username:'supperman',
            },
            content:'欢迎大家在这里给我们提APP相关的建议，产品经理会在这里查看大家的反馈情况。另外使用过程中遇到的问题或疑问，也可以一起提出来哟，帮助我们更好的改进产品~~~',
            replay:[
                {
                    user:'管理员小张',
                    content:'你好，感谢您的建议，我们会在下个版本中改进意见，请您持续关注。'
                },
                {
                    user:'管理员小张',
                    content:'你好，感谢您的建议，我们会在下个版本中改进意见，请您持续关注。'
                },
                {
                    user:'管理员小张',
                    content:'你好，感谢您的建议，我们会在下个版本中改进意见，请您持续关注。'
                }
            ],
            createDate:'2021-12-25',
        },
        {
            id:2,
            user:{
                avatar:'https://axure-file.lanhuapp.com/1bd99c9f-823c-4505-a248-0fe8d210da20__ce77de2733d2f72b27f5abf616a7b5ac.svg',
                username:'supperman',
            },
            content:'欢迎大家在这里给我们提APP相关的建议，产品经理会在这里查看大家的反馈情况。另外使用过程中遇到的问题或疑问，也可以一起提出来哟，帮助我们更好的改进产品~~~',
            replay:[
                {
                    user:'管理员小张',
                    content:'你好，感谢您的建议，我们会在下个版本中改进意见，请您持续关注。'
                },
                {
                    user:'管理员小张',
                    content:'你好，感谢您的建议，我们会在下个版本中改进意见，请您持续关注。'
                },
                {
                    user:'管理员小张',
                    content:'你好，感谢您的建议，我们会在下个版本中改进意见，请您持续关注。'
                }
            ],
            createDate:'2021-12-25',
        }
    ],

    
}