//This file is automatically generated

// 用户属性API

import { UserAttrApiFeignImpl } from '../controller';
export default {
    actions: {
        [UserAttrApiFeignImpl.delete.method] : {
            summary: '根据用户ID,删除属性名称列表',
            method: 'delete',
            url: (payload) => `/api/platform/dal/userAttr/${payload.userid}`,
            parameters: [{'in':'body','name':'attrs','description':'attrs','required':true,'schema':{'type':'array','items':{'$ref':'#/definitions/用户属性信息'}}},{'name':'userid','in':'path','description':'userid','required':true,'type':'string'}],
        },
        [UserAttrApiFeignImpl.get.method] : {
            summary: '根据用户ID获得属性列表',
            method: 'get',
            url: (payload) => `/api/platform/dal/userAttr/${payload.userid}`,
            parameters: [{'name':'userid','in':'path','description':'userid','required':true,'type':'string'}],
        },
        [UserAttrApiFeignImpl.get.method] : {
            summary: '根据用户ID获得属性',
            method: 'get',
            url: (payload) => `/api/platform/dal/userAttr/${payload.userid}/${payload.attrName}`,
            parameters: [{'name':'attrName','in':'path','description':'attrName','required':true,'type':'string'},{'name':'userid','in':'path','description':'userid','required':true,'type':'string'}],
        },
        [UserAttrApiFeignImpl.update.method] : {
            summary: '更新用户属性列表',
            method: 'post',
            url: (payload) => `/api/platform/dal/userAttr/${payload.userid}`,
            parameters: [{'in':'body','name':'attrs','description':'attrs','required':true,'schema':{'type':'array','items':{'$ref':'#/definitions/用户属性信息'}}},{'name':'userid','in':'path','description':'userid','required':true,'type':'string'}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
