//This file is automatically generated

// 日程

import { ScheduleControllerImpl } from '../controller';
export default {
    actions: {
        [ScheduleControllerImpl.addParSchedule.method] : {
            summary: '新增一个参与人日程',
            method: 'post',
            url: (payload) => `/api/platform/schedule/addParSchedule/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'非主键','required':true,'type':'string'},{'in':'body','name':'userVO','description':'userVO','required':true,'schema':{'$ref':'#/definitions/UserVO'}}],
        },
        [ScheduleControllerImpl.addSchedule.method] : {
            summary: '新增一个日程',
            method: 'post',
            url: (payload) => `/api/platform/schedule/addSchedule`,
            parameters: [{'in':'body','name':'scheduleVO','description':'scheduleVO','required':true,'schema':{'$ref':'#/definitions/ScheduleVO'}}],
        },
        [ScheduleControllerImpl.deleteSchedule.method] : {
            summary: '删除一个日程',
            method: 'delete',
            url: (payload) => `/api/platform/schedule/deleteSchedule/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'主键','required':true,'type':'string'}],
        },
        [ScheduleControllerImpl.queryScheduleByMM.method] : {
            summary: '根据时间区间查询日程列表',
            method: 'get',
            url: (payload) => `/api/platform/schedule/queryScheduleByMM/${payload.month}`,
            parameters: [{'name':'month','in':'path','description':'年月','required':true,'type':'string'}],
        },
        [ScheduleControllerImpl.updateAgree.method] : {
            summary: '确认同意或拒绝',
            method: 'put',
            url: (payload) => `/api/platform/schedule/updateAgree/${payload.id}/${payload.agree}`,
            parameters: [{'name':'agree','in':'path','description':'同意或拒绝','required':true,'type':'string'},{'name':'id','in':'path','description':'主键','required':true,'type':'string'}],
        },
        [ScheduleControllerImpl.updateSchedule.method] : {
            summary: '修改一个日程',
            method: 'put',
            url: (payload) => `/api/platform/schedule/updateSchedule/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'主键','required':true,'type':'string'},{'in':'body','name':'scheduleVO','description':'scheduleVO','required':true,'schema':{'$ref':'#/definitions/ScheduleVO'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
