//This file is automatically generated

// 文化建设

import { CulturalController } from '../controller';
export default {
    actions: {
        [CulturalController.addJournalism.method] : {
            summary: '创建新闻/编辑新闻',
            method: 'post',
            url: (payload) => `/api/platform/cultural/addJournalism/${payload.id}`,
            parameters: [{'in':'body','name':'id','description':'新闻id','required':true,'schema':{'$ref':'#/definitions/Journalism'}}],
        },
        [CulturalController.addNotice.method] : {
            summary: '创建公告/编辑公告',
            method: 'post',
            url: (payload) => `/api/platform/cultural/addNotice/${payload.id}`,
            parameters: [{'in':'body','name':'id','description':'公告id','required':true,'schema':{'$ref':'#/definitions/Notice'}}],
        },
        [CulturalController.deleteJournalism.method] : {
            summary: '删除新闻',
            method: 'delete',
            url: (payload) => `/api/platform/cultural/deleteJournalism/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'新闻id','required':true,'type':'string'}],
        },
        [CulturalController.deleteNotice.method] : {
            summary: '删除公告',
            method: 'delete',
            url: (payload) => `/api/platform/cultural/deleteNotice/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'公告id','required':true,'type':'string'}],
        },
        [CulturalController.queryByCulturalDetail.method] : {
            summary: '公告详情',
            method: 'get',
            url: (payload) => `/api/platform/cultural/noticeList/details/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'公告id','required':true,'type':'integer','format':'int32'}],
        },
        [CulturalController.queryByJournalism.method] : {
            summary: '企业新闻',
            method: 'get',
            url: (payload) => `/api/platform/cultural/journalismList`,
            parameters: [{'name':'body','in':'query','required':false,'type':'string'},{'name':'choice','in':'query','required':false,'type':'string'},{'name':'id','in':'query','required':false,'type':'integer','format':'int32'},{'name':'picture','in':'query','required':false,'type':'string'},{'name':'releaseTime.date','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.day','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.hours','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.minutes','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.month','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.nanos','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.seconds','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.time','in':'query','required':false,'type':'integer','format':'int64'},{'name':'releaseTime.timezoneOffset','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.year','in':'query','required':false,'type':'integer','format':'int32'},{'name':'title','in':'query','required':false,'type':'string'},{'name':'type','in':'query','required':false,'type':'string'}],
        },
        [CulturalController.queryByJournalismDetail.method] : {
            summary: '企业新闻详情',
            method: 'get',
            url: (payload) => `/api/platform/cultural/journalismList/details/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'企业新闻id','required':true,'type':'integer','format':'int32'}],
        },
        [CulturalController.queryByPageCultural.method] : {
            summary: '公告列表分页',
            method: 'get',
            url: (payload) => `/api/platform/cultural/noticePageList`,
            parameters: [{'name':'body','in':'query','required':false,'type':'string'},{'name':'id','in':'query','required':false,'type':'integer','format':'int32'},{'in':'body','name':'number','description':'第几页','required':true,'schema':{'type':'integer','format':'int32'}},{'name':'releaseTime.date','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.day','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.hours','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.minutes','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.month','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.nanos','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.seconds','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.time','in':'query','required':false,'type':'integer','format':'int64'},{'name':'releaseTime.timezoneOffset','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.year','in':'query','required':false,'type':'integer','format':'int32'},{'in':'body','name':'size','description':'每一页的数量','required':true,'schema':{'type':'integer','format':'int32'}},{'name':'title','in':'query','required':false,'type':'string'},{'name':'type','in':'query','required':false,'type':'string'}],
        },
        [CulturalController.queryByPageJournalism.method] : {
            summary: '企业新闻分页',
            method: 'get',
            url: (payload) => `/api/platform/cultural/journalismPageList`,
            parameters: [{'name':'body','in':'query','required':false,'type':'string'},{'name':'choice','in':'query','required':false,'type':'string'},{'name':'id','in':'query','required':false,'type':'integer','format':'int32'},{'in':'body','name':'number','description':'第几页','required':true,'schema':{'type':'integer','format':'int32'}},{'name':'picture','in':'query','required':false,'type':'string'},{'name':'releaseTime.date','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.day','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.hours','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.minutes','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.month','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.nanos','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.seconds','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.time','in':'query','required':false,'type':'integer','format':'int64'},{'name':'releaseTime.timezoneOffset','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.year','in':'query','required':false,'type':'integer','format':'int32'},{'in':'body','name':'size','description':'每一页的数量','required':true,'schema':{'type':'integer','format':'int32'}},{'name':'title','in':'query','required':false,'type':'string'},{'name':'type','in':'query','required':false,'type':'string'}],
        },
        [CulturalController.queryByProblem.method] : {
            summary: '公告列表',
            method: 'get',
            url: (payload) => `/api/platform/cultural/noticeList`,
            parameters: [{'name':'body','in':'query','required':false,'type':'string'},{'name':'id','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.date','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.day','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.hours','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.minutes','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.month','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.nanos','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.seconds','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.time','in':'query','required':false,'type':'integer','format':'int64'},{'name':'releaseTime.timezoneOffset','in':'query','required':false,'type':'integer','format':'int32'},{'name':'releaseTime.year','in':'query','required':false,'type':'integer','format':'int32'},{'name':'title','in':'query','required':false,'type':'string'},{'name':'type','in':'query','required':false,'type':'string'}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
