//This file is automatically generated

// demo

import { Demo } from '@controller';
export default {
    actions: {
        [Demo.insert.method] : {
            summary: 'insert',
            method: 'post',
            url: (payload) => `/api/platform/commonProblem/insert/one`,
            parameters: [{'in':'body','name':'commonProblem','description':'commonProblem','required':true,'schema':{'$ref':'#/definitions/CommonProblem'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
