//This file is automatically generated

// demo-user-controller

import { DemoUserController } from '../controller';
export default {
    actions: {
        [DemoUserController.getUser.method] : {
            summary: 'getUser',
            method: 'post',
            url: (payload) => `/api/platform/demoUser/getUser`,
            parameters: [],
        },
        [DemoUserController.isAdmin.method] : {
            summary: 'isAdmin',
            method: 'post',
            url: (payload) => `/api/platform/demoUser/isAdmin`,
            parameters: [],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
