//This file is automatically generated

// 交流圈

import { PipCcoCciController } from '../controller';
export default {
    actions: {
        [PipCcoCciController.addComCir.method] : {
            summary: '发帖子',
            method: 'post',
            url: (payload) => `/api/platform/ccocci/addComCir`,
            parameters: [{'name':'body','in':'query','description':'正文','required':false,'type':'string'},{'name':'choice','in':'query','description':'精选','required':false,'type':'string'},{'in':'body','name':'circle','description':'circle','required':true,'schema':{'$ref':'#/definitions/CommunicationCircle'}},{'name':'fabulous','in':'query','description':'点赞数量','required':false,'type':'ref'},{'name':'id','in':'query','description':'交流圈id','required':false,'type':'string'},{'name':'picture','in':'query','description':'小图','required':false,'type':'string'},{'name':'releaseTime','in':'query','description':'发布时间','required':false,'type':'ref'},{'name':'title','in':'query','description':'标题','required':false,'type':'string'},{'name':'title','in':'query','description':'话题、主题','required':false,'type':'string'},{'name':'top','in':'query','description':'是否置顶','required':false,'type':'ref'},{'name':'topTime','in':'query','description':'置顶时间','required':false,'type':'ref'},{'name':'topicOfConversationId','in':'query','description':'话题id','required':false,'type':'ref'},{'name':'type','in':'query','description':'类型','required':false,'type':'string'},{'name':'userId','in':'query','description':'用户id','required':false,'type':'string'},{'name':'userName','in':'query','description':'用户姓名','required':false,'type':'string'}],
        },
        [PipCcoCciController.addOrDelPra.method] : {
            summary: '根据交流圈id点赞或取消点赞（交流圈下的点赞或者取消点赞）',
            method: 'put',
            url: (payload) => `/api/platform/ccocci/addOrDelPra/${payload.id}`,
            parameters: [{'name':'id','in':'query','description':'交流圈id','required':true,'type':'string'}],
        },
        [PipCcoCciController.addOrDelPraComment.method] : {
            summary: '根据交流圈评论id点赞或取消点赞（评论下的点赞或者取消点赞）',
            method: 'put',
            url: (payload) => `/api/platform/ccocci/addOrDelPraComment/${payload.id}`,
            parameters: [{'name':'id','in':'query','description':'交流圈评论id','required':true,'type':'string'}],
        },
        [PipCcoCciController.delCommentById.method] : {
            summary: '根据交流圈评论id删除评论',
            method: 'get',
            url: (payload) => `/api/platform/ccocci/delCommentById`,
            parameters: [{'name':'id','in':'query','description':'交流圈评论id','required':true,'type':'string'}],
        },
        [PipCcoCciController.selAllComment.method] : {
            summary: '根据交流圈id交流圈详情',
            method: 'get',
            url: (payload) => `/api/platform/ccocci/selAllComment`,
            parameters: [{'name':'id','in':'query','description':'交流圈id','required':true,'type':'string'}],
        },
        [PipCcoCciController.selComCilList.method] : {
            summary: '交流圈列表List(type:1全部加载排序，2热度点赞评论数量排序，3精华帖排序，4按话题排序，5置顶排序)',
            method: 'get',
            url: (payload) => `/api/platform/ccocci/selComCilList`,
            parameters: [{'name':'body','in':'query','description':'正文','required':false,'type':'string'},{'name':'choice','in':'query','description':'精选','required':false,'type':'string'},{'in':'body','name':'circle','description':'circle','required':true,'schema':{'$ref':'#/definitions/CommunicationCircle'}},{'name':'fabulous','in':'query','description':'点赞数量','required':false,'type':'ref'},{'name':'id','in':'query','description':'交流圈id','required':false,'type':'string'},{'name':'picture','in':'query','description':'小图','required':false,'type':'string'},{'name':'releaseTime','in':'query','description':'发布时间','required':false,'type':'ref'},{'name':'title','in':'query','description':'标题','required':false,'type':'string'},{'name':'top','in':'query','description':'是否置顶','required':false,'type':'ref'},{'name':'topTime','in':'query','description':'置顶时间','required':false,'type':'ref'},{'name':'topicOfConversationId','in':'query','description':'话题id','required':false,'type':'ref'},{'name':'type','in':'query','description':'类型','required':true,'type':'string'},{'name':'userId','in':'query','description':'用户id','required':false,'type':'string'},{'name':'userName','in':'query','description':'用户姓名','required':false,'type':'string'}],
        },
        [PipCcoCciController.selComCilPageSortList.method] : {
            summary: '交流圈列表List(按条件模糊查询。按日期倒叙排序)',
            method: 'get',
            url: (payload) => `/api/platform/ccocci/selComCilPageSortList`,
            parameters: [{'name':'body','in':'query','description':'正文','required':false,'type':'string'},{'name':'choice','in':'query','description':'精选','required':false,'type':'string'},{'in':'body','name':'dto','description':'dto','required':true,'schema':{'$ref':'#/definitions/CommunicationCircleDTO'}},{'name':'fabulous','in':'query','description':'点赞数量','required':false,'type':'ref'},{'name':'id','in':'query','description':'交流圈id','required':false,'type':'string'},{'name':'pageNum','in':'query','description':'页数','required':true,'type':'ref'},{'name':'pageSize','in':'query','description':'记录数','required':true,'type':'ref'},{'name':'picture','in':'query','description':'小图','required':false,'type':'string'},{'name':'releaseTime','in':'query','description':'发布时间','required':false,'type':'ref'},{'name':'title','in':'query','description':'标题','required':false,'type':'string'},{'name':'title','in':'query','description':'话题、主题','required':false,'type':'string'},{'name':'top','in':'query','description':'是否置顶','required':false,'type':'ref'},{'name':'topTime','in':'query','description':'置顶时间','required':false,'type':'ref'},{'name':'topicOfConversationId','in':'query','description':'话题id','required':false,'type':'ref'},{'name':'type','in':'query','description':'类型','required':false,'type':'string'},{'name':'userId','in':'query','description':'用户id','required':false,'type':'string'},{'name':'userName','in':'query','description':'用户姓名','required':false,'type':'string'}],
        },
        [PipCcoCciController.selCommentById.method] : {
            summary: '根据交流圈id查询关联的评论',
            method: 'get',
            url: (payload) => `/api/platform/ccocci/selCommentById`,
            parameters: [{'name':'id','in':'query','description':'交流圈id','required':true,'type':'ref'},{'name':'pageNum','in':'query','description':'交流圈评论id','required':true,'type':'ref'},{'name':'pageSize','in':'query','description':'交流圈评论id','required':true,'type':'ref'}],
        },
        [PipCcoCciController.selCommentCircle.method] : {
            summary: '根据交流圈id加载交流圈详情)',
            method: 'get',
            url: (payload) => `/api/platform/ccocci/selCommentCircle`,
            parameters: [{'name':'id','in':'query','description':'交流圈id','required':false,'type':'string'}],
        },
        [PipCcoCciController.selCommentDetailsList.method] : {
            summary: '根据交流圈id查看评论信息)',
            method: 'get',
            url: (payload) => `/api/platform/ccocci/selCommentDetailsList`,
            parameters: [{'name':'id','in':'query','description':'交流圈id','required':false,'type':'string'}],
        },
        [PipCcoCciController.topOne.method] : {
            summary: '根据交流圈id置顶交流圈',
            method: 'delete',
            url: (payload) => `/api/platform/ccocci/topOne/${payload.id}`,
            parameters: [{'name':'id','in':'query','description':'交流圈id','required':true,'type':'string'}],
        },
        [PipCcoCciController.upCommentById.method] : {
            summary: '根据交流圈评论id更新评论',
            method: 'put',
            url: (payload) => `/api/platform/ccocci/upCommentById`,
            parameters: [{'name':'body','in':'query','description':'用户id','required':false,'type':'string'},{'name':'commentTime','in':'query','description':'用户姓名','required':false,'type':'ref'},{'name':'communicationCircleId','in':'query','description':'交流圈id','required':false,'type':'ref'},{'in':'body','name':'dto','description':'dto','required':true,'schema':{'$ref':'#/definitions/CommunicationCircleComment'}},{'name':'fabulous','in':'query','description':'正文','required':false,'type':'ref'},{'name':'id','in':'query','description':'交流圈评论id','required':true,'type':'string'},{'name':'userId','in':'query','description':'类型','required':false,'type':'string'},{'name':'userName','in':'query','description':'标题','required':false,'type':'string'}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
